/* 炸彈女僕 BOMB MAIDS — interface text. key: 中文 source → [日本語, English] */
(function (G) {
  'use strict';
  G.addTr({
    // ---- in-stage popups
    '炸彈+1': ['ボム+1', 'Bomb +1'],
    '火力+1': ['火力+1', 'Fire +1'],
    '速度+1': ['スピード+1', 'Speed +1'],
    '愛心+1': ['ハート+1', 'Heart +1'],
    '時間暫停！': ['時間停止！', 'Time Stop!'],
    '無敵！': ['無敵！', 'Invincible!'],
    '特技全滿': ['特技MAX', 'Skill MAX'],
    '打掃+1': ['おそうじ+1', 'Clean +1'],
    '愛的守護！': ['愛のまもり！', 'Love Shield!'],
    '拆除！': ['解体！', 'Defused!'],
    '護盾破了！': ['シールドが割れた！', 'Shield broke!'],
    '爆裂飛踢！': ['バクレツキック！', 'Blast Kick!'],
    '緊急清場！': ['緊急そうじ！', 'Sudden Death!'],

    // ---- title
    '開始冒險': ['ぼうけん開始', 'Start'],
    '跳過 ▶▶': ['スキップ ▶▶', 'Skip ▶▶'],
    '女僕對決': ['メイド対決', 'Maid Battle'],
    '卡片圖鑑': ['カード図鑑', 'Card Album'],
    '設定': ['設定', 'Settings'],
    '炸彈女僕': ['爆弾メイド', 'BOMB MAIDS'],
    '～ 蕾絲咖啡廳的大掃除 ～': ['～ レース喫茶の大そうじ ～', '~ The Lace Cafe Cleanup ~'],
    '點一下畫面，或按 Z / Enter 開始': ['タップ、または Z / Enter でスタート', 'Tap the screen or press Z / Enter'],
    '音效　{v}': ['効果音　{v}', 'Sound  {v}'],
    '音樂　{v}': ['BGM　{v}', 'Music  {v}'],
    '語言　{v}': ['言語　{v}', 'Language  {v}'],
    '開': ['ON', 'ON'],
    '關': ['OFF', 'OFF'],
    '清除存檔': ['データ消去', 'Delete Save'],
    '返回': ['もどる', 'Back'],
    '確定要清除所有進度嗎？': ['すべてのデータを消しますか？', 'Delete all progress?'],
    'Z 清除　X 取消': ['Z 消す　X やめる', 'Z Delete   X Cancel'],

    // ---- maid select / hire
    '金幣不夠……還差 {n}G': ['コインが足りない…あと {n}G', 'Not enough coins... {n}G short'],
    '值班中': ['お仕え中', 'On duty'],
    '特技「{skill}」': ['特技「{skill}」', 'Skill: {skill}'],
    '愛心 {n}': ['ハート {n}', 'Hearts {n}'],
    '「{line}」': ['「{line}」', '"{line}"'],
    '←→ 選擇　Z 決定　X 返回': ['←→ えらぶ　Z 決定　X もどる', '←→ Choose  Z OK  X Back'],

    // ---- job board
    '委託看板': ['依頼ボード', 'Job Board'],
    '體力': ['体力', 'STA'],
    '完成上一個委託後解鎖': ['前の依頼をクリアで解放', 'Clear the previous job first'],
    '委託人：{client}': ['依頼人：{client}', 'Client: {client}'],
    '報酬': ['報酬', 'Reward'],
    '時限 {time}': ['制限 {time}', 'Time {time}'],
    '出現怪物': ['出現モンスター', 'Monsters'],
    '最佳評價': ['ベスト評価', 'Best rank'],
    '已點餐點：': ['注文ずみ：', 'Ordered:'],
    '女僕太累了！先回房間休息吧': ['メイドがへとへと…お部屋で休もう', 'Your maid is worn out. Rest first!'],
    'Z 出發（體力 -{n}）　X 回房間　ESC 標題': ['Z 出発（体力-{n}）　X お部屋　ESC タイトル', 'Z Go (-{n} STA)  X Room  ESC Title'],
    '？？？': ['？？？', '???'],

    // ---- café
    '甜點補給': ['スイーツ', 'Sweets'],
    '禮物專櫃': ['プレゼント', 'Gifts'],
    '家具店': ['家具屋', 'Furniture'],
    '女僕強化': ['メイド強化', 'Upgrades'],
    '扭蛋機': ['ガチャ', 'Gacha'],
    '回房間': ['お部屋へ', 'My Room'],
    '已經點過囉，下個委託會送上。': ['注文ずみです。次の依頼で出しますね。', 'Already ordered. It comes with the next job.'],
    '金幣不夠……': ['コインが足りない…', 'Not enough coins...'],
    '{name} 點好了！{desc}': ['{name}を注文！{desc}', 'Ordered {name}! {desc}'],
    '買了{name}！回房間送給女僕吧。': ['{name}を買った！お部屋でプレゼントしよう。', 'Bought {name}! Give it to your maid.'],
    '房間裡已經有{name}了。': ['{name}はもう持っています。', 'You already own the {name}.'],
    '{name} 已經搬進房間了！': ['{name}をお部屋に置きました！', '{name} is in your room now!'],
    '{name} 放進倉庫了（房間太擠）': ['{name}は倉庫へ（お部屋がいっぱい）', '{name} went to storage (room is full)'],
    '已經強化到最高級了！': ['もう最大まで強化ずみ！', 'Already at max level!'],
    '{name} 強化到 Lv.{lv}！': ['{name}が Lv.{lv} に！', '{name} is now Lv.{lv}!'],
    '需要 {n}G 才能轉扭蛋。': ['ガチャは {n}G 必要です。', 'Gacha costs {n}G.'],
    '女僕咖啡廳「蕾絲炸彈」': ['メイド喫茶「レースボム」', 'Maid Cafe "Lace Bomb"'],
    '按 Z 前往更衣室': ['Z で控え室へ', 'Press Z to go'],
    '回到自己的房間': ['自分のお部屋にもどる', 'Back to your room'],
    '↑↓ 選擇　Z 決定　X 回房間': ['↑↓ えらぶ　Z 決定　X お部屋', '↑↓ Choose  Z OK  X Room'],
    'Z 轉扭蛋　X 返回': ['Z ガチャを回す　X もどる', 'Z Spin  X Back'],
    '方向鍵 選擇　Z 購買　X 返回': ['十字キー えらぶ　Z 買う　X もどる', 'Arrows Choose  Z Buy  X Back'],
    '↑↓ 選擇　Z 購買　X 返回': ['↑↓ えらぶ　Z 買う　X もどる', '↑↓ Choose  Z Buy  X Back'],
    '回房間送給女僕': ['お部屋でプレゼント', 'Give them at home'],
    '大家都喜歡': ['みんな大好き', 'Everyone loves'],
    '{name}最愛': ['{name}の好物', '{name} loves it'],
    '持有 {n}': ['所持 {n}', 'Own {n}'],
    '買了會自動搬進房間': ['買うとお部屋に届きます', 'Delivered to your room'],
    '已擁有': ['所持ずみ', 'Owned'],
    '效果只維持到下一個委託': ['効果は次の依頼だけ', 'Lasts for the next job'],
    '已點': ['注文ずみ', 'Ordered'],
    '永久效果': ['ずっと有効', 'Permanent'],
    '收集 {n}/{total}': ['収集 {n}/{total}', 'Found {n}/{total}'],
    '轉一次': ['1回', 'One spin'],
    '抽出怪物卡或女僕卡！重複的卡會退還 30G。': ['モンスターかメイドのカードが出る！ダブりは30G返却。', 'Win monster or maid cards! Duplicates refund 30G.'],
    '按 Z 轉扭蛋！': ['Z で回そう！', 'Press Z to spin!'],
    '按 → 或 Z 進入': ['→ か Z でえらぶ', 'Press → or Z'],
    '重複了！退還 30G': ['ダブり！30G返却', 'Duplicate! 30G back'],
    'NEW! 已加入卡片圖鑑': ['NEW! 図鑑に登録', 'NEW! Added to album'],
    '按 Z 繼續': ['Z でつぎへ', 'Press Z'],
    '喜歡{like}，興趣是{hobby}。': ['好物は{like}、趣味は{hobby}。', 'Loves {like}. Hobby: {hobby}.'],

    // ---- album
    '持有 ×{n}': ['所持 ×{n}', 'Owned x{n}'],
    '還沒有抽到這張卡。': ['まだ持っていないカードです。', "You haven't found this card yet."],
    '到咖啡廳的扭蛋機試試手氣吧！': ['メイド喫茶のガチャで運試し！', 'Try your luck at the cafe gacha!'],
    '方向鍵 選擇　X 返回': ['十字キー えらぶ　X もどる', 'Arrows Choose  X Back'],

    // ---- stage tips
    '掃起灰塵可以累積特技，打掃度越高評價越好。': ['ホコリを掃くと特技がたまる。きれいにするほど高評価！', 'Sweeping dust charges your skill and raises your rank.'],
    '最後一隻怪物倒下前，記得把灰塵掃乾淨！': ['最後のモンスターを倒す前にホコリを掃除しよう！', 'Clean up the dust before the last monster falls!'],
    '炸彈的火焰會引爆其他炸彈，形成連鎖爆炸。': ['爆風はほかのボムに引火して連鎖爆発する。', 'Blasts set off other bombs for chain explosions.'],
    '到咖啡廳點甜點，下個委託會更輕鬆。': ['喫茶店でスイーツを頼むと次の依頼が楽になる。', 'Order sweets at the cafe to power up the next job.'],
    '時間剩 30 秒時，怪物會變得更快！': ['残り30秒でモンスターが速くなる！', 'Monsters speed up in the last 30 seconds!'],

    // ---- stage tutorial card
    '女僕的工作守則': ['メイドのお仕事ルール', "A Maid's Work Rules"],
    '{key} 放炸彈，火焰呈十字炸開。': ['{key} でボム。爆風は十字に広がる。', '{key}: drop a bomb. It blasts in a cross.'],
    '{key} 使用女僕特技（消耗 SP）。': ['{key} でメイド特技（SPを使う）。', '{key}: use your maid skill (costs SP).'],
    '打倒全部怪物就能完成委託。': ['モンスターを全部倒せば依頼クリア。', 'Defeat every monster to finish the job.'],
    '炸開家具會掉出道具，記得撿！': ['家具を壊すとアイテムが出る！', 'Broken furniture can hide power-ups!'],
    '掃起灰塵可以累積 SP，打掃度越高，評價和報酬越好。': ['ホコリを掃くとSPがたまり、そうじ度が高いほど評価と報酬アップ。', 'Sweeping dust fills SP. Cleaner rooms mean better ranks and pay.'],
    '按 A 開始工作': ['A でお仕事スタート', 'Press A to start'],
    '按 Z 開始工作': ['Z でお仕事スタート', 'Press Z to start'],

    // ---- stage HUD and overlays
    '金熊機甲': ['金熊メカ', 'Gold Bear Mech'],
    '委託完成！': ['依頼クリア！', 'Job Done!'],
    '時間到了……': ['時間切れ…', "Time's up..."],
    '被炸飛了……': ['ふっとばされた…', 'Blown away...'],
    '暫停': ['ポーズ', 'Pause'],
    '繼續': ['つづける', 'Resume'],
    '重新開始': ['やりなおす', 'Restart'],
    '放棄委託': ['依頼をやめる', 'Quit job'],
    '打掃度': ['そうじ度', 'Clean'],
    'A 放炸彈': ['A ボム', 'A Bomb'],
    'Z 放炸彈': ['Z ボム', 'Z Bomb'],
    'B 特技': ['B 特技', 'B Skill'],
    'X 特技': ['X 特技', 'X Skill'],
    '||暫停': ['||ポーズ', '|| Pause'],
    'ESC 暫停': ['ESC ポーズ', 'ESC Pause'],

    // ---- results / game over
    '評價・好感加成': ['評価・好感ボーナス', 'Rank & bond bonus'],
    '委託報酬': ['依頼の報酬', 'Job reward'],
    '撿到的金幣': ['拾ったコイン', 'Coins found'],
    '打掃度 {n}%': ['そうじ度 {n}%', 'Clean {n}%'],
    '剩餘時間 {n}秒': ['残り時間 {n}秒', 'Time left {n}s'],
    '受傷次數 {n}': ['ダメージ {n}回', 'Hits taken {n}'],
    '委託結算': ['依頼の結果', 'Job Results'],
    '合計': ['合計', 'Total'],
    '完美的女僕！': ['パーフェクトメイド！', 'Perfect maid!'],
    '非常優秀！': ['とても優秀！', 'Excellent!'],
    '做得不錯！': ['よくできました！', 'Nice work!'],
    '再加油喔！': ['つぎはがんばろう！', 'Keep trying!'],
    '好感度 +{n}': ['好感度 +{n}', 'Affection +{n}'],
    'Z 繼續': ['Z つぎへ', 'Z Next'],
    'Z 回房間': ['Z お部屋へ', 'Z Back to room'],
    '委託失敗……': ['依頼失敗…', 'Job Failed...'],
    '時間到了，灰塵還沒掃完。': ['時間切れ。ホコリが残ってしまった。', "Time ran out before the dust was gone."],
    '被炸得黑漆漆的……': ['爆風でまっ黒こげ…', 'Burnt to a crisp...'],
    '撿到的金幣留下一半：+{n}G': ['拾ったコインの半分：+{n}G', 'You keep half the coins: +{n}G'],
    '體力不足，先回房間休息吧': ['体力が足りない。お部屋で休もう', 'Not enough stamina. Rest first.'],
    '再試一次（體力 -{n}）': ['もう一度（体力-{n}）', 'Retry (-{n} STA)'],

    // ---- ending
    '金熊機甲停下來了。': ['金熊メカが止まった。', 'The Gold Bear Mech powers down.'],
    '原來，機甲裡的小熊只是想要': ['メカの中の小さなクマは、', 'The little bear inside only wanted'],
    '一間永遠乾乾淨淨的房間。': ['ずっときれいな部屋がほしかっただけ。', 'a room that stays clean forever.'],
    '「那就來咖啡廳吧。」{maid}笑著說。': ['「じゃあ喫茶店においでよ」と{maid}が笑う。', '"Then come to our cafe," {maid} smiles.'],
    '「我們每天都會打掃喔！」': ['「毎日おそうじしますから！」', '"We clean every single day!"'],
    '從此以後，蕾絲炸彈咖啡廳': ['それからレースボムには、', 'And so the Lace Bomb cafe'],
    '多了一位毛茸茸的常客。': ['もふもふの常連さんが増えました。', 'gained a fluffy regular.'],
    '— 炸彈女僕 BOMB MAIDS —': ['— 爆弾メイド BOMB MAIDS —', '— BOMB MAIDS —'],
    '感謝遊玩！': ['遊んでくれてありがとう！', 'Thanks for playing!'],
    '（所有委託都能重玩刷評價，': ['（依頼は何度でも挑戦できます。', '(Replay any job for a better rank,'],
    '　也別忘了收集卡片喔）': ['　カード集めもお忘れなく）', ' and keep collecting cards!)'],

    // ---- battle setup / battle
    '玩家人數': ['プレイヤー人数', 'Players'],
    '1P 女僕': ['1P メイド', '1P Maid'],
    '2P 女僕': ['2P メイド', '2P Maid'],
    '電腦女僕': ['CPUメイド', 'CPU Maids'],
    '{n} 位': ['{n}人', '{n}'],
    '電腦強度': ['CPUの強さ', 'CPU Level'],
    '普通': ['ふつう', 'Normal'],
    '厲害': ['つよい', 'Strong'],
    '勝利條件': ['勝利条件', 'To Win'],
    '先贏 {n} 局': ['先に{n}勝', 'First to {n}'],
    '開始對決！': ['対決スタート！', 'Start Battle!'],
    '在咖啡廳大廳一決勝負！': ['喫茶店のホールで勝負！', 'Showdown in the cafe hall!'],
    '2P  方向鍵・K・L': ['2P  十字キー・K・L', '2P  Arrows・K・L'],
    '方向鍵 移動': ['十字キー 移動', 'Arrows Move'],
    'Z 炸彈　X 特技': ['Z ボム　X 特技', 'Z Bomb  X Skill'],
    '↑↓ 選擇　←→ 變更　Z 決定　X 返回': ['↑↓ えらぶ　←→ 変更　Z 決定　X もどる', '↑↓ Choose  ←→ Change  Z OK  X Back'],
    '先贏 {n} 局的女僕獲勝': ['先に{n}勝したメイドの勝ち', 'First maid to {n} wins'],
    '外圈開始封鎖！往中間移動！': ['外側がふさがる！中央へ急げ！', 'The edges are closing! Move inward!'],
    '最後站著的女僕就是贏家': ['最後まで残ったメイドの勝ち', 'Last maid standing wins'],
    '{name} 贏了這一局！': ['{name}がこのラウンドの勝者！', '{name} wins the round!'],
    '平手！': ['引き分け！', 'Draw!'],
    '離開對決': ['対決をやめる', 'Leave battle'],
    '{name}（{who}）是最強的女僕！': ['{name}（{who}）が最強のメイド！', '{name} ({who}) is the strongest maid!'],
    'Z 回到對決設定': ['Z 対決設定にもどる', 'Z Back to setup'],

    // ---- room
    '開心': ['ごきげん', 'Happy'],
    '低落': ['しょぼん', 'Down'],
    '很沮喪': ['どんより', 'Gloomy'],
    '日記': ['日記', 'Diary'],
    '休息': ['おやすみ', 'Rest'],
    '出門': ['おでかけ', 'Go out'],
    '衣櫃': ['クローゼット', 'Closet'],
    '系統': ['システム', 'System'],
    '佈置': ['もようがえ', 'Decorate'],
    '這裡就是主人的房間嗎？我會每天打掃得亮晶晶的！': ['ここがご主人さまのお部屋ですか？毎日ぴかぴかにおそうじしますね！', "So this is your room, Master? I'll keep it sparkling every day!"],
    '在房間裡照顧女僕、陪她說話，她就會越來越信賴你，出任務時也會更強喔。': ['お部屋でお世話をしたりお話ししたりすると信頼が深まり、依頼でも強くなります。', 'Care for her and talk with her here. Her trust grows, and so does her strength on jobs.'],
    '小任務完成！+{n}G': ['ミッション達成！+{n}G', 'Mission done! +{n}G'],
    '沒有可以送的禮物……到女僕咖啡廳的「禮物專櫃」買一點吧！': ['あげられるプレゼントがない…メイド喫茶の「プレゼント」で買おう！', 'No gifts yet... Buy some at the cafe gift counter!'],
    '送什麼禮物？': ['何をプレゼントする？', 'Which gift?'],
    '要進行哪種特訓？（體力 {n}）': ['どの特訓をする？（体力 {n}）', 'Which training? (STA {n})'],
    '體力-{n}': ['体力-{n}', '-{n} STA'],
    '愛心上限': ['ハート上限', 'Max hearts'],
    '速度': ['スピード', 'Speed'],
    '火力': ['火力', 'Fire'],
    '炸彈': ['ボム', 'Bombs'],
    '今天已經喝過下午茶了，明天再一起喝吧！': ['今日はもうお茶しましたよ。また明日いっしょに！', 'We already had tea today. Tomorrow again!'],
    '茶葉要 30G……金幣不夠。': ['茶葉は30G…コインが足りない。', 'Tea leaves cost 30G... not enough coins.'],
    '今天已經彈過囉～': ['今日はもう弾きましたよ～', 'I already played today~'],
    '要休息到明天嗎？': ['明日まで休みますか？', 'Rest until tomorrow?'],
    '休息（進入第 {n} 天）': ['休む（{n}日目へ）', 'Rest (go to day {n})'],
    '還不要': ['まだいい', 'Not yet'],
    '獲得「{name}」': ['「{name}」をもらった', 'Got {name}'],
    '要去哪裡？': ['どこへ行く？', 'Where to?'],
    '女僕咖啡廳': ['メイド喫茶', 'Maid Cafe'],
    '取消': ['やめる', 'Cancel'],
    '體力不夠出任務了。先讓她休息到明天吧。': ['依頼に行く体力がない。明日まで休ませてあげよう。', "She's too tired for a job. Let her rest until tomorrow."],
    '音效：{v}': ['効果音：{v}', 'Sound: {v}'],
    '音樂：{v}': ['BGM：{v}', 'Music: {v}'],
    '回到標題': ['タイトルへ', 'Title screen'],
    '關閉': ['閉じる', 'Close'],
    '聊天': ['おしゃべり', 'Talk'],
    '送禮物': ['プレゼント', 'Give gift'],
    '特訓': ['特訓', 'Train'],
    '一起喝茶（30G）': ['いっしょにお茶（30G）', 'Tea time (30G)'],
    '查看成長日記': ['成長日記を見る', 'Growth diary'],
    '{name}　好感 Lv{lv}': ['{name}　好感 Lv{lv}', '{name}  Bond Lv{lv}'],
    '今天已經澆過水了！': ['今日はもう水やりしました！', 'Already watered today!'],
    '盆栽今天也要長高高喔♪': ['今日も大きくなあれ♪', 'Grow big today too♪'],
    '兔兔抱枕軟綿綿的～': ['うさぎクッション、ふわふわ～', 'The bunny cushion is so soft~'],
    '借我抱一下兔兔嘛～': ['うさちゃん、ぎゅってさせて～', 'Let me hug the bunny~'],
    '燈光好溫暖呢。': ['あったかい灯りですね。', 'Such a warm light.'],
    '移動家具': ['家具を動かす', 'Move furniture'],
    '選擇房間裡的家具，搬到別的位置。': ['お部屋の家具をえらんで別の場所へ。', 'Pick up a piece and move it.'],
    '從倉庫擺進房間。': ['倉庫からお部屋に置く。', 'Place it from storage. '],
    '壁紙': ['壁紙', 'Wallpaper'],
    '更換房間的壁紙。': ['お部屋の壁紙を変える。', 'Change the wallpaper.'],
    '地板': ['床', 'Floor'],
    '更換房間的地板。': ['お部屋の床を変える。', 'Change the floor.'],
    '擴建': ['増築', 'Expand'],
    '已最大': ['最大', 'Max size'],
    '擴建成{name}（{w}×{h}）：{price}G': ['{name}（{w}×{h}）に増築：{price}G', 'Expand to {name} ({w}x{h}): {price}G'],
    '房間已經是最大了。': ['お部屋はもう最大です。', 'The room is already as big as it gets.'],
    '完成': ['完了', 'Done'],
    '結束佈置。': ['もようがえを終わる。', 'Finish decorating.'],
    '擴建成{name}？': ['{name}に増築する？', 'Expand to {name}?'],
    '擴建（{price}G）': ['増築する（{price}G）', 'Expand ({price}G)'],
    '房間變大了！': ['お部屋が広くなった！', 'The room got bigger!'],
    '（使用中）': ['（使用中）', ' (in use)'],
    '摸摸頭': ['なでなで', 'Pat head'],
    '戳戳臉頰': ['ほっぺをつんつん', 'Poke her cheek'],
    '擊掌': ['ハイタッチ', 'High five'],
    '搔癢': ['くすぐる', 'Tickle'],
    '和{name}互動': ['{name}とふれあう', 'Spend time with {name}'],
    '換班': ['交代', 'Switch'],
    '喝茶': ['お茶', 'Tea'],
    '彈琴': ['ピアノ', 'Piano'],
    '澆水': ['水やり', 'Water'],
    '抱抱': ['ぎゅっ', 'Hug'],
    '看看': ['ながめる', 'Look'],
    '叫她過來': ['ここに呼ぶ', 'Call her here'],
    '窗外天氣真好': ['いいお天気', 'Nice weather out there'],
    '今天天氣很好呢～': ['今日はいいお天気ですね～', 'Lovely weather today~'],
    '心情 +20　體力 +10': ['気分+20　体力+10', 'Mood +20  STA +10'],
    '心情': ['気分', 'Mood'],
    '第 {n} 天': ['{n}日目', 'Day {n}'],
    '拖曳手套、點一下互動　B 功能列': ['手ぶくろを動かしてタップでふれあう　B メニュー', 'Move the glove, tap to interact  B Menu'],
    'Z 互動　X 功能列　ESC 系統　滑鼠也可以直接點': ['Z ふれあう　X メニュー　ESC システム　マウスでもクリックできます', 'Z Interact  X Menu  ESC System  You can also click with the mouse'],
    '好感度提升！': ['好感度アップ！', 'Affection up!'],
    '{name} 完成！': ['{name} 完了！', '{name} done!'],
    '經驗值 +{n}': ['経験値 +{n}', 'EXP +{n}'],
    '（心情加成）': ['（ごきげんボーナス）', ' (mood bonus)'],
    '（心情低落）': ['（しょんぼり）', ' (feeling down)'],
    '能力提升了！': ['能力がアップ！', 'Stats went up!'],
    '體力 -{n}': ['体力 -{n}', 'STA -{n}'],
    '早安！大家的體力都恢復了。': ['おはよう！みんなの体力が回復した。', "Good morning! Everyone's stamina is back."],
    '{name}的成長日記': ['{name}の成長日記', "{name}'s Growth Diary"],
    '{name}的特技': ['{name}の特技', "{name}'s Skills"],
    '被動特性': ['パッシブ', 'Passive'],
    '主動特技': ['アクティブ特技', 'Skill'],
    '消耗 SP {n}': ['SP消費 {n}', 'SP cost {n}'],
    '對戰小技巧': ['バトルのコツ', 'Battle tip'],
    '▲▼ 翻頁': ['▲▼ ページ', '▲▼ Page'],
    '成長': ['成長', 'Growth'],
    '愛心': ['ハート', 'Hearts'],
    '第 {day} 天　出任務 {jobs} 次': ['{day}日目　依頼 {jobs}回', 'Day {day}  Jobs {jobs}'],
    '好感度 Lv{lv}「{name}」': ['好感度 Lv{lv}「{name}」', 'Affection Lv{lv} {name}'],
    '出任務時　炸彈{b}　火力{f}　速度{s}　愛心{h}　SP消耗{sp}': ['依頼時　ボム{b}　火力{f}　速さ{s}　ハート{h}　SP{sp}', 'On jobs  Bomb{b} Fire{f} Spd{s} Heart{h} SP{sp}'],
    '擺放：{name}': ['置く：{name}', 'Place: {name}'],
    '選擇要移動的家具': ['動かす家具をえらんでね', 'Choose furniture to move'],
    '　（←→ 選擇　Z 決定　X 結束）': ['　（←→ えらぶ　Z 決定　X 終了）', '  (←→ Choose  Z OK  X Exit)'],
    '方向鍵移動　Z 放下　X 取消（綠色可以放）': ['十字キー移動　Z 置く　X やめる（緑なら置けます）', 'Arrows move  Z place  X cancel (green = OK)'],
    '方向鍵選格子　Z 拿起　X 返回': ['十字キーでマスをえらぶ　Z 持つ　X もどる', 'Arrows pick a tile  Z lift  X back'],
    '移': ['移', 'MV'],
    '壁': ['壁', 'WL'],
    '地': ['床', 'FL'],
    '擴': ['増', '+'],
    '完': ['完', 'OK'],

    // ---- maids join through jobs, furniture shop in the room
    '女僕換班': ['メイド交代', 'Switch Maid'],
    '夥伴 {n}/{total}': ['仲間 {n}/{total}', 'Maids {n}/{total}'],
    '←→ 選擇　Z 值班　X 返回': ['←→ えらぶ　Z 交代　X もどる', '←→ Choose  Z Switch  X Back'],
    '打倒怪物 ×{n}': ['モンスター退治 ×{n}', 'Monsters x{n}'],
    '新夥伴 {name} 加入了！': ['{name}が仲間になった！', 'New maid {name} joined!'],
    '{name}成為新的夥伴了！打開衣櫃就能換她值班。': ['{name}が仲間になりました！クローゼットで交代できます。', '{name} is on the team now! Use the wardrobe to switch.'],
    '金魚已經吃飽囉～': ['金魚はもうおなかいっぱい～', 'The goldfish is full~'],
    '小金魚，開飯囉～': ['金魚さん、ごはんですよ～', 'Dinner time, little fish~'],
    '今天已經打扮好了！': ['今日のおめかしは完璧です！', 'I\'m all dressed up today!'],
    '緞帶綁好了……主人，好看嗎？': ['リボン、結べました…ご主人さま、似合いますか？', 'Ribbon tied... Do I look cute, Master?'],
    '沙發好舒服……不過今天已經休息夠了。': ['ソファ気持ちいい…でも今日はもう十分休みました。', 'So comfy... but I rested enough today.'],
    '呼～坐一下，體力恢復了！': ['ふう～ひと休みで体力回復！', 'Phew~ A short sit and I feel better!'],
    '體力 +{n}': ['体力 +{n}', 'STA +{n}'],
    '再聽一次這張唱片吧♪': ['このレコード、もう一回聴きましょう♪', 'Let\'s play this record again♪'],
    '放一張唱片吧♪': ['レコードをかけましょう♪', 'Let\'s put on a record♪'],
    '{name}（{price}G）': ['{name}（{price}G）', '{name} ({price}G)'],
    '　Z 購買': ['　Z 買う', '  Z Buy'],
    '要買{name}嗎？': ['{name}を買う？', 'Buy {name}?'],
    '購買（{price}G）': ['買う（{price}G）', 'Buy ({price}G)'],
    '買了{name}！選個位置擺放吧': ['{name}を買った！置く場所をえらぼう', 'Bought {name}! Pick a spot'],

    // ---- bosses unlock maids, outfits
    '第一位女僕': ['最初のメイド', 'Your First Maid'],
    '每打倒一個 BOSS，就有一位女僕加入': ['BOSSを倒すたびにメイドが1人加入', 'Each boss beaten brings a maid'],
    '打倒 {id}': ['{id} 撃破', 'Beat {id}'],
    '每打倒一個 BOSS，就有新的女僕加入。在這裡可以讓她們換班。': ['BOSSを倒すたびに新しいメイドが仲間に。ここで交代もできます。', 'Each boss you beat brings a new maid. Switch who is on duty here.'],
    '換衣服': ['着替え', 'Change Outfit'],
    '要讓{name}穿哪件？': ['{name}に何を着せる？', 'What should {name} wear?'],
    '穿著中': ['着用中', 'Wearing'],
    '現在就穿著這件喔！': ['今これを着ていますよ！', 'I\'m already wearing this!'],
    '換好了！主人，好看嗎？': ['着替えました！ご主人さま、似合いますか？', 'All changed! Do I look nice, Master?'],

    '打倒{id}「{title}」後，就會有新的女僕加入！': ['{id}「{title}」を倒すと新しいメイドが仲間に！', 'Defeat {id} "{title}" and a new maid joins!'],
    '打倒後有新女僕加入！': ['倒すと新メイド加入！', 'New maid on victory!'],
    '打倒 {id} 就會加入。': ['{id}を倒すと仲間になります。', 'Joins after you beat {id}.'],
    '還沒加入的神秘女僕。': ['まだ仲間になっていない、なぞのメイド。', 'A mysterious maid who has not joined yet.'],

    // ---- page (outside the canvas)
    '全螢幕': ['全画面', 'Fullscreen'],
    '橫向遊玩': ['横向きで遊ぶ', 'Play sideways'],
    '無法切換成全螢幕。': ['全画面にできませんでした。', 'Couldn\'t switch to fullscreen.'],
    '這個瀏覽器不支援全螢幕。iPhone 請點「分享」→「加入主畫面」，從主畫面打開就能全螢幕遊玩。': ['このブラウザは全画面に対応していません。iPhoneは「共有」→「ホーム画面に追加」から開くと全画面で遊べます。', 'This browser can\'t go fullscreen. On iPhone, tap Share → Add to Home Screen, then open the game from the home screen.'],
    '炸彈女僕 遊戲畫面，使用方向鍵移動、Z 放炸彈、X 使用特技': ['爆弾メイドのゲーム画面。十字キーで移動、Zでボム、Xで特技', 'BOMB MAIDS game screen. Arrow keys move, Z drops a bomb, X uses a skill'],
    '方向鍵': ['十字キー', 'Arrows'],
    '移動': ['移動', 'Move'],
    '放炸彈 / 決定': ['ボム / 決定', 'Bomb / OK'],
    '特技 / 返回': ['特技 / もどる', 'Skill / Back'],
    '房間裡可以直接用滑鼠點女僕和家具': ['お部屋ではマウスでメイドや家具をクリックできます', 'In your room, click the maid and furniture'],
    '支援手把・雙人對決 1P WASD+F/G、2P 方向鍵+K/L': ['ゲームパッド対応・2人対決 1P WASD+F/G、2P 十字キー+K/L', 'Gamepads OK · 2P battle: 1P WASD+F/G, 2P Arrows+K/L'],
    '特技': ['特技', 'Skill'],
    // ---- the real clock, the weekday and resting
    '週日': ['日', 'Sun'],
    '週一': ['月', 'Mon'],
    '週二': ['火', 'Tue'],
    '週三': ['水', 'Wed'],
    '週四': ['木', 'Thu'],
    '週五': ['金', 'Fri'],
    '週六': ['土', 'Sat'],
    '休息中體力恢復了 +{n}': ['休んでいる間に体力が +{n} 回復', 'Rested: stamina +{n}'],
    '體力每小時恢復 {n}': ['体力は1時間に{n}ずつ回復します', 'Stamina recovers {n} per hour'],
  });
})(window);
