/* 炸彈女僕 BOMB MAIDS — data & dialogue text. key: 中文 source → [日本語, English] */
(function (G) {
  'use strict';
  G.addTr({
    // ---- maids
    '莓果': ['ベリー', 'Berry'],
    '空手道': ['空手', 'karate'],
    '草莓大福': ['いちご大福', 'Berry Mochi'],
    '今天也要元氣滿滿地打掃！': ['今日も元気いっぱいおそうじです！', "Let's clean with all our might today!"],
    '夜子': ['夜子', 'Yoru'],
    '劍道': ['剣道', 'kendo'],
    '抹茶': ['抹茶', 'matcha'],
    '居合斬': ['居合斬り', 'Iai Slash'],
    '主人，請退後。灰塵由我來斬。': ['ご主人さま、お下がりを。ホコリは私が斬ります。', 'Stand back, Master. I shall cut the dust.'],
    '蜜糖': ['ハニー', 'Honey'],
    '烤點心': ['お菓子作り', 'baking'],
    '蜂蜜蛋糕': ['ハニーケーキ', 'Honey Cake'],
    '甜心魔法': ['スイート魔法', 'Sweet Magic'],
    '點心烤好了～怪物們也乖乖的喔♪': ['お菓子が焼けました～モンスターさんもいい子にね♪', 'Treats are ready~ Be good, monsters♪'],
    '雪乃': ['雪乃', 'Yukino'],
    '讀書': ['読書', 'reading'],
    '冰淇淋': ['アイス', 'ice cream'],
    '遙控引爆': ['リモコン起爆', 'Remote Blast'],
    '計算完畢。爆破時機，完美。': ['計算完了。爆破のタイミング、完璧です。', 'Calculation complete. Perfect blast timing.'],
    // roles, passives and skills (reworked)
    '突擊型': ['突撃タイプ', 'Striker'],
    '斬擊型': ['斬撃タイプ', 'Blade'],
    '支援型': ['サポートタイプ', 'Support'],
    '戰術型': ['戦術タイプ', 'Tactician'],
    '踢飛炸彈': ['ボムキック', 'Bomb Kick'],
    '走向炸彈就能把它踢飛。': ['ボムに向かって歩くとけり飛ばせる。', 'Walk into a bomb to kick it away.'],
    '爆裂飛踢': ['バクレツキック', 'Blast Kick'],
    '把面前的炸彈用力踢出（沒有就先放一顆），': ['目の前のボムを思いきりけり出し（なければ置いてからキック）、', 'Kicks the bomb in front hard (dropping one first if there is none); '],
    '撞到東西就立刻爆炸。': ['何かにぶつかった瞬間に爆発する。', 'it bursts the moment it hits something.'],
    '一刀兩斷': ['一刀両断', 'Clean Cut'],
    '她的爆炸火焰能貫穿一個木箱繼續延伸。': ['彼女の爆風は木箱をひとつ貫いてさらにのびる。', 'Her blasts cut through one crate and keep going.'],
    '斬開面前兩格的木箱與怪物，': ['目の前2マスの木箱とモンスターを斬り、', 'Cuts crates and monsters up to two tiles ahead, '],
    '連炸彈也能一刀拆除。': ['ボムもひと太刀で解体する。', 'and defuses bombs with one stroke.'],
    '糖霜護盾': ['シュガーシールド', 'Sugar Shield'],
    '護盾能擋下一次傷害，': ['シールドがダメージを1回ふせぎ、', 'Her shield blocks one hit, '],
    '破掉後過一陣子會重新長出來。': ['割れてもしばらくするとまた張られる。', 'and grows back a while after it breaks.'],
    '回復 1 顆愛心並立刻補好護盾，': ['ハートを1つ回復してシールドもすぐ張りなおし、', 'Restores a heart and rebuilds her shield at once; '],
    '附近的怪物和對手會暈頭轉向。': ['近くのモンスターやライバルをメロメロにする。', 'nearby monsters and rivals get dazed.'],
    '冰晶爆破': ['アイスクリスタル', 'Frost Blast'],
    '爆炸旁邊的怪物會被凍住，': ['爆風のとなりのモンスターは凍りつき、', 'Monsters beside her blasts freeze, '],
    '對手則會被寒氣拖慢腳步。': ['ライバルは冷気で足が遅くなる。', 'and rivals are slowed by the chill.'],
    '立刻引爆自己放下的所有炸彈，': ['自分のボムを全部すぐに起爆し、', 'Sets off all her bombs at once; '],
    '遙控引爆時火力 +1。': ['リモコン起爆のボムは火力+1。', 'remote blasts reach one tile further.'],
    '踢出的炸彈撞到東西就爆炸，別站在它的火線上！': ['けったボムはぶつかると爆発。爆風の線上に立たないで！', 'A kicked bomb bursts where it hits. Stay out of its line!'],
    '腳步慢但火力強，居合斬能拆掉滑過來的炸彈。': ['足は遅いが火力は強い。居合斬りでせまるボムも解体。', 'Slow but strong. Her slash defuses bombs sliding at her.'],
    '用魔法暈住對手，靠護盾爭取反擊時間。對戰中護盾長得慢。': ['魔法でまひさせ、シールドで反撃の時間をかせぐ。対戦では回復がおそい。', 'Daze rivals and let the shield buy time. It regrows slowly in battles.'],
    '先放炸彈，等對手靠近再遙控引爆，寒氣會拖住逃跑的人。': ['ボムを置いて、近づいたらリモコン起爆。冷気で逃げる相手を足止め。', 'Set bombs, then remote-blast as rivals come close. The chill slows runners.'],

    // ---- monsters
    '塵塵貓': ['ホコリネコ', 'Dust Cat'],
    '住在課桌底下的灰塵團。': ['机の下にすむホコリのかたまり。', 'A dust bunny living under desks.'],
    '貪吃豬': ['くいしんブタ', 'Glutton Pig'],
    '把福利社的麵包吃光光。': ['購買部のパンを食べつくした。', 'Ate every roll in the school store.'],
    '暴走熊': ['ぼうそうクマ', 'Rampage Bear'],
    '會追著女僕跑的布偶熊。': ['メイドを追いかけるぬいぐるみ。', 'A stuffed bear that chases maids.'],
    '果凍怪': ['ぷるぷるゼリー', 'Jelly Blob'],
    '能穿過家具的軟Q果凍。': ['家具をすり抜けるゼリー。', 'A wobbly jelly that slips through furniture.'],
    '企鵝紳士': ['ペンギン紳士', 'Sir Penguin'],
    '一旦開跑就停不下來。': ['走り出したら止まらない。', 'Once he runs, he never stops.'],
    '雪寶寶': ['ゆきんこ', 'Snow Kid'],
    '會躲開炸彈的聰明雪人。': ['ボムをよける賢い雪だるま。', 'A clever snowman that dodges bombs.'],
    '杯子蛋糕怪': ['カップケーキ魔', 'Cupcake Fiend'],
    '奶油很厚，要炸兩次。': ['クリームが厚くて2回当てないと倒せない。', 'Thick frosting. Takes two hits.'],
    '糖果龍': ['アメドラゴン', 'Candy Dragon'],
    '檸檬冠毛的甜點守衛。': ['レモンのとさかのお菓子の番人。', 'A dessert guard with a lemon crest.'],

    // ---- jobs
    '教室大掃除': ['教室大そうじ', 'Class Cleanup'],
    '櫻丘學園 校長': ['桜丘学園の校長先生', 'Principal, Sakuraoka School'],
    '放學後的教室被塵塵貓佔領了。': ['放課後の教室がホコリネコに占領された。', 'Dust Cats took over the classroom after school.'],
    '請把牠們通通清掉！': ['全部やっつけてください！', 'Please clear them all out!'],
    '福利社的貪吃鬼': ['パンどろぼう', 'Snack Thief'],
    '學生會長': ['生徒会長', 'Student Council President'],
    '福利社的麵包被吃光了！': ['購買部のパンが食べられた！', 'Every roll in the school store is gone!'],
    '犯人好像是粉紅色的……': ['犯人はピンク色らしい…', 'The culprit seems to be pink...'],
    '玫瑰花園除蟲': ['花園パニック', 'Rose Garden'],
    '花園伯爵夫人': ['庭園の伯爵夫人', 'The Garden Countess'],
    '暴走熊在玫瑰園裡橫衝直撞。': ['ぼうそうクマがバラ園であばれている。', 'Rampage Bears are running wild in the roses.'],
    '別讓牠們弄壞樹屋！': ['ツリーハウスを壊させないで！', "Don't let them wreck the tree house!"],
    '果凍迷宮': ['ゼリーの迷宮', 'Jelly Maze'],
    '園丁老爺爺': ['庭師のおじいさん', 'The Old Gardener'],
    '果凍怪會穿過花叢！': ['ゼリーは花だんをすり抜ける！', 'Jellies slip right through the flowerbeds!'],
    '聽說牠們最怕長長的火力。': ['長い爆風が苦手らしい。', 'They say long blasts scare them.'],
    '雪原的企鵝管家': ['ペンギン執事', 'Penguin Butler'],
    '冰雪山莊': ['氷雪の山荘', 'Snowy Lodge'],
    '企鵝紳士跑得飛快。': ['ペンギン紳士はとても速い。', 'Sir Penguin runs very fast.'],
    '在牠的路上等著放炸彈吧。': ['通り道にボムを置いて待とう。', 'Wait on his path with a bomb.'],
    '聰明的雪寶寶': ['天才雪ん子', 'Clever Snowkids'],
    '雪寶寶會躲炸彈。': ['ゆきんこはボムをよける。', 'Snow Kids dodge bombs.'],
    '用連環爆炸把牠逼進死角！': ['連鎖爆発で追いつめよう！', 'Corner them with chain blasts!'],
    '糖果城堡的午茶': ['お城のお茶会', 'Castle Teatime'],
    '甜點女王': ['スイーツ女王', 'The Dessert Queen'],
    '杯子蛋糕怪的奶油很厚，': ['カップケーキ魔はクリームが厚く、', 'Cupcake Fiends have thick frosting, '],
    '要炸兩次才會投降。': ['2回当てないと降参しない。', 'so they need two hits.'],
    '甜點大暴走': ['スイーツ暴走', 'Dessert Riot'],
    '糖果龍帶著大軍來了！': ['アメドラゴンが大軍を連れてきた！', 'Candy Dragons brought an army!'],
    '這是最後的甜點防衛戰。': ['最後のお菓子防衛戦です。', 'This is the final dessert defense.'],
    '所有灰塵的源頭——': ['すべてのホコリの元凶——', 'The source of all the dust:'],
    '神秘研究所的巨大機甲！': ['なぞの研究所の巨大メカ！', ' a giant mech in a secret lab!'],

    // ---- café menu, upgrades, cards
    '草莓蛋糕': ['いちごケーキ', 'Strawberry Cake'],
    '下個委託 愛心 +1': ['次の依頼 ハート+1', 'Next job: Hearts +1'],
    '焦糖布丁': ['カラメルプリン', 'Caramel Pudding'],
    '下個委託 火力 +1': ['次の依頼 火力+1', 'Next job: Fire +1'],
    '冰拿鐵': ['アイスラテ', 'Iced Latte'],
    '下個委託 速度 +1': ['次の依頼 スピード+1', 'Next job: Speed +1'],
    '伯爵紅茶': ['アールグレイ', 'Earl Grey'],
    '下個委託 開場特技全滿': ['次の依頼 特技MAXで開始', 'Next job: start with full SP'],
    '炸彈提籃': ['ボムかご', 'Bomb Basket'],
    '炸彈數量 +1': ['ボムの数+1', 'Bombs +1'],
    '火力掃把': ['火力ほうき', 'Fire Broom'],
    '火力 +1': ['火力+1', 'Fire +1'],
    '輕盈皮鞋': ['かるい靴', 'Light Shoes'],
    '速度 +1': ['スピード+1', 'Speed +1'],
    '蕾絲圍裙': ['エプロン', 'Lace Apron'],
    '愛心上限 +1': ['ハート上限+1', 'Max hearts +1'],
    '研究所的最終兵器。': ['研究所の最終兵器。', "The lab's ultimate weapon."],
    '女僕炸彈': ['メイドボム', 'Maid Bomb'],
    '戴著蕾絲髮箍的炸彈。': ['レースのカチューシャをつけたボム。', 'A bomb wearing a lace headband.'],

    // ---- room
    '小房間': ['小さいお部屋', 'Small room'],
    '中房間': ['ふつうのお部屋', 'Medium room'],
    '大房間': ['広いお部屋', 'Large room'],
    '兔兔壁紙': ['うさぎ壁紙', 'Bunny'],
    '草莓牛奶條紋': ['いちごミルク柄', 'Berry Milk Stripes'],
    '草莓點點': ['いちごドット', 'Strawberry Dots'],
    '星空壁紙': ['星空壁紙', 'Starry Night'],
    '木地板': ['木の床', 'Wood'],
    '粉紅地毯': ['ピンクのじゅうたん', 'Pink Carpet'],
    '格子磁磚': ['チェックのタイル', 'Checker Tile'],
    '小木床': ['木のベッド', 'Wooden Bed'],
    '在這裡休息到隔天。': ['ここで明日まで休む。', 'Rest here until morning.'],
    '公主床': ['お姫さまベッド', 'Princess Bed'],
    '睡醒時心情 +15。': ['起きたとき気分+15。', 'Wake up with Mood +15.'],
    '書桌': ['つくえ', 'Desk'],
    '在這裡進行特訓。': ['ここで特訓する。', 'Train here.'],
    '下午茶桌': ['ティーテーブル', 'Tea Table'],
    '可以一起喝下午茶。': ['いっしょにお茶できる。', 'Have tea together.'],
    '書櫃': ['本だな', 'Bookshelf'],
    '特訓經驗值 +20%。': ['特訓の経験値+20%。', 'Training EXP +20%.'],
    '盆栽': ['はち植え', 'Potted Plant'],
    '澆水讓心情變好。': ['水やりで気分アップ。', 'Watering lifts the mood.'],
    '兔兔抱枕': ['うさぎクッション', 'Bunny Cushion'],
    '摸頭時好感度多 +1。': ['なでなでで好感度+1。', 'Head pats give +1 more affection.'],
    '愛心地毯': ['ハートのラグ', 'Heart Rug'],
    '心情不容易變差。': ['気分が下がりにくい。', 'Mood drops more slowly.'],
    '小鋼琴': ['小さなピアノ', 'Little Piano'],
    '每天聽女僕彈一曲。': ['毎日1曲弾いてくれる。', 'She plays you a song each day.'],
    '立燈': ['フロアランプ', 'Floor Lamp'],
    '溫暖的燈光。': ['あたたかい灯り。', 'A warm glow.'],
    '鼓鼓兔': ['ドラムうさぎ', 'Drum Bunny'],
    '敲著小鼓追過來的兔子。': ['小太鼓をたたいて追いかけてくる。', 'Chases you while banging its drum.'],
    '寶石騎士': ['ジュエルナイト', 'Gem Knight'],
    '盔甲很硬，要炸兩次。': ['よろいが硬く、2回当てないと倒れない。', 'Hard armor: it takes two blasts.'],
    '城堡地下出現了噴火的機械蜘蛛！': ['お菓子城の地下に火をふく機械グモ！', 'A fire-breathing robot spider under the castle!'],
    '玩具箱演唱會': ['おもちゃライブ', 'Toy Box Concert'],
    '玩具店老闆': ['おもちゃ屋の店長', 'Toy Shop Owner'],
    '玩具們在舞台上開起了演唱會！': ['おもちゃたちがステージでライブ中！', 'The toys are putting on a concert!'],
    '鼓鼓兔會追著人跑，小心被包圍。': ['ドラムうさぎは追ってくる。囲まれないで。', 'Drum Bunnies chase you. Don\'t get surrounded.'],
    '積木迷宮': ['つみき迷路', 'Block Maze'],
    '積木塔堆成了迷宮。': ['つみきの塔が迷路になっている。', 'Block towers form a maze.'],
    '用炸彈打通一條路吧！': ['ボムで道をひらこう！', 'Blast a path through!'],
    '寶石宮殿': ['ジュエルパレス', 'Jewel Palace'],
    '寶石公主': ['宝石のお姫さま', 'Jewel Princess'],
    '宮殿中央的巨大寶石蛋被盯上了！': ['宮殿の宝石たまごが狙われている！', 'The palace\'s giant jewel egg is in danger!'],
    '寶石騎士很硬，要炸兩次。': ['ジュエルナイトは2回当てよう。', 'Gem Knights take two hits.'],
    '閃耀迴廊': ['きらめき回廊', 'Crystal Hall'],
    '水晶柱排成菱形的迴廊。': ['水晶の柱がひし形に並ぶ回廊。', 'Crystal pillars form a diamond.'],
    '從四個缺口鑽進中央吧！': ['4つのすき間から中へ入ろう！', 'Slip in through the four gaps!'],
    '女僕裝': ['メイド服', 'Maid Uniform'],
    '蕾絲咖啡廳的制服。': ['レース喫茶の制服。', 'The Lace Cafe uniform.'],
    '黑貓女僕裝': ['黒ネコメイド', 'Black Cat Maid'],
    '毛茸茸的貓耳朵是重點！': ['ふわふわのネコ耳がポイント！', 'The fluffy cat ears are the best part!'],
    '夏日浴衣': ['夏のゆかた', 'Summer Yukata'],
    '別上髮花的祭典浴衣。': ['髪に花を飾ったお祭りゆかた。', 'A festival yukata with a hair flower.'],
    '公主洋裝': ['プリンセスドレス', 'Princess Dress'],
    '閃亮亮的小皇冠。': ['キラキラの小さなティアラつき。', 'Comes with a sparkly tiara.'],
    '鑽頭機器人': ['ドリルロボ', 'Drill Bot'],
    '理科社社長': ['科学部の部長', 'Science Club Head'],
    '理科社的掃除機器人失控了！': ['科学部のそうじロボが暴走！', 'The science robot ran wild!'],
    '牠撞到硬牆會暈一下，趁機炸牠！': ['壁にぶつけて目を回したら攻撃！', 'Make it crash, then bomb it while dizzy!'],
    '火焰蜘蛛': ['ほのおグモ', 'Flame Spider'],
    '火焰沿著直線噴出，別跟牠站同一排！': ['炎はまっすぐ飛ぶ。同じ列はキケン！', 'Stay out of its row and column.'],
    '理科社做的掃除機器人。': ['科学部が作ったそうじロボ。', 'A cleaning robot built by the Science Club.'],
    '頭上燒著火焰的機械蜘蛛。': ['頭に炎を燃やす機械グモ。', 'A robot spider with a fire on its head.'],
    '讓別的女僕來值班。': ['ほかのメイドと交代する。', 'Switch the maid on duty.'],
    '金魚缸': ['金魚鉢', 'Fishbowl'],
    '每天餵魚，心情 +4。': ['毎日エサやりで気分 +4。', 'Feed it daily: mood +4.'],
    '梳妝台': ['ドレッサー', 'Vanity'],
    '每天梳妝打扮，心情 +6。': ['毎日おめかしで気分 +6。', 'Dress up daily: mood +6.'],
    '愛心沙發': ['ハートソファ', 'Heart Sofa'],
    '每天坐著休息，體力 +15。': ['毎日ひと休みで体力 +15。', 'Rest daily: STA +15.'],
    '留聲機': ['蓄音機', 'Gramophone'],
    '播放唱片，心情 +5。': ['レコードで気分 +5。', 'Play a record: mood +5.'],
    '用賺到的金幣買家具吧！點右上角的「佈置」': ['稼いだコインで家具を買おう！右上の「もようがえ」から', 'Buy furniture with your coins! Tap Decorate (top right)'],
    '抹茶羊羹': ['抹茶ようかん', 'Matcha Yokan'],
    '香草冰淇淋': ['バニラアイス', 'Vanilla Ice'],
    '玫瑰花束': ['バラの花束', 'Rose Bouquet'],
    '蕾絲髮帶': ['レースリボン', 'Lace Ribbon'],

    // ---- affection & training
    '陌生': ['初対面', 'Stranger'],
    '熟悉': ['顔なじみ', 'Familiar'],
    '委託開始時 SP +20': ['依頼開始時 SP+20', 'Start jobs with SP +20'],
    '信賴': ['信頼', 'Trusted'],
    '委託中愛心 +1': ['依頼中ハート+1', 'Hearts +1 on jobs'],
    '親密': ['仲良し', 'Close'],
    '委託報酬 +20%': ['依頼の報酬+20%', 'Job rewards +20%'],
    '最愛': ['大好き', 'Beloved'],
    '愛的守護：每次委託免死一次': ['愛のまもり：依頼で1回耐える', 'Love Shield: survive 1 fatal hit a job'],
    '體能鍛鍊': ['体力づくり', 'Fitness'],
    'Lv2/4 愛心+1': ['Lv2/4 ハート+1', 'Lv2/4 Heart+1'],
    '愛心上限 +1（Lv2、Lv4）': ['ハート上限+1（Lv2・Lv4）', 'Max hearts +1 (Lv2, Lv4)'],
    '敏捷訓練': ['ダッシュ', 'Agility'],
    'Lv2/5 速度+1': ['Lv2/5 スピード+1', 'Lv2/5 Speed+1'],
    '速度 +1（Lv2、Lv5），受傷後無敵更久': ['スピード+1（Lv2・Lv5）、ダメージ後の無敵が長くなる', 'Speed +1 (Lv2, Lv5), longer invincibility after hits'],
    '爆破研究': ['ボム研究', 'Bomb Lab'],
    'Lv2 火力 Lv4 炸彈': ['Lv2火力 Lv4ボム', 'Lv2 Fire Lv4 Bomb'],
    '火力 +1（Lv2）、炸彈 +1（Lv4）': ['火力+1（Lv2）・ボム+1（Lv4）', 'Fire +1 (Lv2), Bombs +1 (Lv4)'],
    '家事練習': ['家事練習', 'Chores'],
    '打掃獎勵・省SP': ['そうじ報酬・SP節約', 'Dust bonus, SP saver'],
    '掃灰塵獎勵變多，特技更省 SP（Lv3、Lv5）': ['ホコリの報酬アップ、特技のSPが減る（Lv3・Lv5）', 'More from dust, cheaper skills (Lv3, Lv5)'],

    // ---- opening, guide, mornings
    '「蕾絲町」——一座被灰塵怪佔領的小鎮。': ['「レース町」——ホコリおばけに占領された小さな町。', 'Lace Town: a little town overrun by dust monsters.'],
    '你搬進洋館裡的一間小房間，成為新的主人。': ['あなたは洋館の小さな部屋に越してきた、新しいご主人さま。', 'You just moved into a small room in the old mansion.'],
    '為了打掃小鎮、賺點生活費……': ['町をきれいにして、生活費をかせぐため…', 'To clean up the town and earn a living...'],
    '你決定雇用一位女僕！': ['メイドを雇うことにした！', 'you decide to hire a maid!'],
    '把手套移到女僕頭上按 Z，摸摸她的頭': ['手ぶくろをメイドの頭に合わせて Z でなでなで', "Move the glove onto her head and press Z to pat"],
    '點女僕的身體打開選單，和她聊聊天': ['メイドの体をクリックしてメニューからおしゃべり', 'Click her body to open the menu, then talk'],
    '點書桌進行特訓，讓她變得更強': ['つくえをクリックして特訓しよう', 'Click the desk to train her'],
    '點下方的門口出門，接下第一個委託吧': ['下のドアからおでかけして、最初の依頼へ', 'Leave through the door below for your first job'],
    '{maid}烤了點心要送給你！': ['{maid}がお菓子を焼いてくれた！', '{maid} baked you a treat!'],
    '在床底下撿到了 40G！': ['ベッドの下で40G見つけた！', 'Found 40G under the bed!'],
    '{maid}一早就把房間擦得亮晶晶。': ['{maid}が朝からお部屋をぴかぴかに。', '{maid} polished the room this morning.'],
    '{maid}泡了早安紅茶，心情很好。': ['{maid}がモーニングティーをいれてごきげん。', '{maid} made morning tea and feels great.'],

    // ---- Berry: energetic karate girl
    '初次見面！我是莓果！從今天起就是主人的女僕了，請多指教！': ['はじめまして！ベリーです！今日からご主人さまのメイドです、よろしくお願いしますっ！', "Nice to meet you! I'm Berry, your maid from today on!"],
    '欸嘿嘿……被摸頭了～': ['えへへ…なでなでされちゃった～', 'Ehehe... a head pat~'],
    // poke, high five and tickle reactions
    '呀！主人，偷襲犯規啦！': ['ひゃっ！ご主人さま、不意打ちは反則だよ！', 'Eek! Master, sneak attacks are against the rules!'],
    '嘿嘿，戳臉頰好癢喔～': ['えへへ、ほっぺつんつん、くすぐったい～', 'Ehehe, cheek pokes tickle~'],
    '再戳下去，莓果要反擊囉！': ['これ以上つついたら、ベリー反撃しちゃうよ！', 'Poke me again and Berry fights back!'],
    '耶——！擊掌！我們是最強搭檔！': ['いぇーい！ハイタッチ！最強コンビだね！', 'Yeah! High five! We\'re the best team!'],
    '好痛快！再來一次！': ['スカッとした！もう一回！', 'That felt great! One more!'],
    '哈哈哈！住手、住手啦主人！': ['あはは！やめて、やめてってばご主人さま！', 'Hahaha! Stop, stop it, Master!'],
    '呀哈哈！我、我最怕癢了！': ['きゃはは！く、くすぐりは苦手なの！', 'Kyahaha! I-I\'m super ticklish!'],
    '呼……呼……笑到肚子好痛……今天不行了！': ['はぁ…はぁ…笑いすぎておなか痛い…今日はもう無理！', 'Huff... huff... my tummy hurts from laughing... no more today!'],
    '唔、主人的手好溫暖……': ['ん、ご主人さまの手、あったかい…', "Mm, your hand is so warm..."],
    '再、再摸一下也可以喔！': ['も、もう一回なでてもいいですよ！', 'Y-you can pat me once more!'],
    '主人，頭髮要被摸亂啦！': ['ご主人さま、髪がぐしゃぐしゃになっちゃう！', "Master, you're messing up my hair!"],
    '好、好了啦！夠了夠了！': ['も、もういいです！おしまい！', "O-okay! That's enough!"],
    '我小時候在道場練了十年空手道！': ['子どものころ、道場で10年空手をやってたんです！', 'I trained karate at a dojo for ten years!'],
    '打掃跟練拳一樣，靠的是氣勢！': ['おそうじも空手も、気合いが大事！', "Cleaning is like karate. It's all spirit!"],
    '主人的房間有點亂耶，我來整理！': ['お部屋がちょっと散らかってますね、片づけます！', "Your room's a little messy. I'll tidy up!"],
    '主人喜歡草莓嗎？我超喜歡的！': ['ご主人さま、いちご好きですか？私は大好き！', 'Do you like strawberries? I love them!'],
    '上次委託，我踢飛了好多炸彈喔！': ['この前の依頼、ボムをいっぱいけり飛ばしました！', 'I kicked so many bombs on the last job!'],
    '跟主人說話，心情就會變好呢！': ['ご主人さまと話すと元気が出ます！', 'Talking with you always cheers me up!'],
    '就算怪物再多，我也會保護主人！': ['モンスターがいくらいても、ご主人さまを守ります！', "No matter how many monsters come, I'll protect you!"],
    '主人，我們是最棒的搭檔對吧？': ['ご主人さま、私たち最高のコンビですよね？', "We're the best team, right, Master?"],
    '偷偷告訴你，我其實很怕打雷……': ['ないしょですけど、実はカミナリが苦手で…', "Between us... I'm actually scared of thunder..."],
    '能當主人的女僕，真的太好了。': ['ご主人さまのメイドになれて、本当によかった。', "I'm really glad I became your maid."],
    '主人……今天也可以待在我身邊嗎？': ['ご主人さま…今日もそばにいてくれますか？', 'Master... will you stay by my side today too?'],
    '最喜歡主人了！……啊，說出來了！': ['ご主人さま大好き！…あっ、言っちゃった！', 'I love you, Master! ...Ah, I said it!'],
    '不管去哪裡，莓果都跟著主人喔！': ['どこへでも、ベリーはご主人さまについていきます！', "Wherever you go, Berry's coming too!"],
    '今天聊好多喔！剩下的明天再說吧♪': ['今日はいっぱい話しました！続きはまた明日♪', "We talked so much today! More tomorrow♪"],
    '草莓大福！主人怎麼知道我最愛這個！': ['いちご大福！どうして大好物だってわかったんですか！', "Berry mochi! How did you know it's my favorite?!"],
    '謝謝主人！我會好好珍惜的！': ['ありがとうございます！大事にしますね！', "Thank you, Master! I'll treasure it!"],
    '今天收到好多禮物了，留到明天嘛！': ['今日はもうたくさんもらいました、また明日！', "I got plenty today. Save it for tomorrow!"],
    '呼～和主人喝茶好幸福喔。': ['ふぅ～ご主人さまとのお茶、しあわせです。', 'Phew~ Tea with you is the best.'],
    '呼……主人，讓我休息一下嘛……': ['はぁ…ご主人さま、ちょっと休ませて…', 'Huff... Master, let me rest a bit...'],
    '好！特訓開始！看我的！': ['よーし！特訓開始！見ててください！', "Okay! Training starts now! Watch me!"],
    '呼！流了好多汗，感覺變強了！': ['ふぅ！いい汗かいた、強くなった気がします！', "Whew! Good sweat. I feel stronger!"],
    '莓果，出擊！主人等我好消息！': ['ベリー、出撃！いい知らせを待っててください！', "Berry, heading out! Wait for good news!"],
    '我回來了！委託順利完成～': ['ただいまです！依頼ばっちり完了～', "I'm back! Job complete~"],
    '嗚嗚……被炸得黑漆漆的……': ['うう…まっ黒こげです…', 'Ugh... burnt to a crisp...'],
    '主人晚安……明天見……': ['おやすみなさい…また明日…', 'Good night, Master... see you tomorrow...'],
    '和主人的距離，好像又更近了一點呢！': ['ご主人さまとの距離、また近づいた気がします！', 'I feel even closer to you now!'],
    '嘿嘿，我只會彈「小星星」啦♪': ['えへへ、「きらきら星」しか弾けないんです♪', 'Hehe, I only know "Twinkle Twinkle"♪'],

    // ---- Yoru: stoic swordswoman

    // ---- Honey: sweet baker
    '主人好～我是蜜糖！以後每天都做點心給主人吃喔♪': ['ご主人さま～ハニーです！毎日お菓子を作ってあげますね♪', "Hi, Master~ I'm Honey! I'll bake treats for you every day♪"],
    '嗚嗚……奶油都烤焦了……': ['うう…クリームがこげちゃった…', 'Waah... my frosting got burnt...'],
    '晚安，主人～夢裡也要一起吃蛋糕喔♪': ['おやすみなさい～夢の中でもケーキ食べようね♪', "Good night~ Let's eat cake in our dreams too♪"],
    '主人對蜜糖的好感度……爆表了♪': ['ご主人さまへの好き、あふれちゃった♪', 'My love for you just overflowed♪'],
    '這首曲子叫「鬆餅圓舞曲」喔♪': ['この曲は「パンケーキのワルツ」です♪', 'This one is called "Pancake Waltz"♪'],

    // ---- Yukino: cool, bookish, a little tsundere

    // ---- greetings by the hour, the weekday and the sky
    '主人早安！今天也從打掃開始吧！': ['ご主人さま、おはようございます！今日もお掃除からいきましょう！', 'Morning, Master! Let us start with the cleaning again today!'],
    '主人午安！中午了，要不要吃點什麼？': ['ご主人さま、こんにちは！お昼ですよ、何か食べます？', 'Afternoon, Master! It is noon — want something to eat?'],
    '主人，太陽快下山了，今天也辛苦了！': ['ご主人さま、もう日が暮れますね。今日もお疲れさまでした！', 'Master, the sun is going down. Good work today!'],
    '這麼晚還沒睡？莓果陪主人到你想睡為止！': ['こんな時間まで起きてるんですか？ベリーが眠くなるまで付き合いますよ！', 'Still up this late? Berry will stay up with you as long as you like!'],
    '平日的主人也很努力呢，我也要加油！': ['平日のご主人さまもがんばってますね。わたしも負けません！', 'You work hard on weekdays too, Master. I will not fall behind!'],
    '今天是假日耶！要不要一起出門走走？': ['今日はお休みですね！一緒にお出かけしませんか？', 'It is a day off! Shall we go out somewhere together?'],
    '今天天氣真好！把被子拿去曬一曬吧！': ['いいお天気！お布団を干しちゃいましょう！', 'What great weather! Let us air out the futons!'],
    '陰陰的天氣，打掃起來反而不會熱呢。': ['曇りだと、お掃除しても暑くなくていいですね。', 'Cloudy days are nice — cleaning does not get you sweaty.'],
    '下雨了……不過雨聲聽起來很舒服對吧？': ['雨ですね……でも雨の音って気持ちいいですよね？', 'It is raining... but the sound is kind of nice, right?'],
    '下雪了！主人，等一下來堆雪人嘛！': ['雪だ！ご主人さま、あとで雪だるま作りましょうよ！', 'Snow! Master, let us build a snowman later!'],


    '主人早安～今天的紅茶已經泡好囉♪': ['ご主人さま、おはようございます～紅茶はもう淹れてありますよ♪', 'Morning, Master~ The tea is already brewed♪'],
    '主人午安～要不要休息一下吃塊蛋糕？': ['ご主人さま、こんにちは～ひと休みにケーキはいかがですか？', 'Afternoon, Master~ How about a break and a slice of cake?'],
    '傍晚了呢～主人晚餐想吃什麼呀？': ['夕方ですね～ご主人さま、晩ごはんは何がいいですか？', 'It is evening~ What would you like for dinner, Master?'],
    '夜深了喔，別太勉強……蜜糖陪著主人♪': ['もう遅いですよ、無理しないで……ハニーがそばにいますから♪', 'It is late — do not push yourself... Honey is right here♪'],
    '平日辛苦了～回到這裡就好好放鬆吧♪': ['平日はお疲れさまです～ここではゆっくりしてくださいね♪', 'Weekdays are tiring~ Please relax while you are here♪'],
    '今天是假日呢～要慢慢過，還是出去玩？': ['今日はお休みですね～のんびりします？それともお出かけ？', 'It is a day off~ Take it slow, or go out somewhere?'],
    '陽光好舒服～小兔子也在曬太陽呢♪': ['日差しが気持ちいい～うさぎさんも日向ぼっこしてますよ♪', 'The sun feels lovely~ Even the bunny is sunbathing♪'],
    '雲有點多呢，出門記得帶把傘喔。': ['雲が多いですね。お出かけには傘をお忘れなく。', 'Rather cloudy. Do not forget an umbrella if you go out.'],
    '雨天的午後，最適合配紅茶了♪': ['雨の午後は、紅茶がいちばん合いますね♪', 'A rainy afternoon goes best with tea♪'],
    '下雪了……主人，手會不會冷呀？': ['雪ですね……ご主人さま、手は冷たくないですか？', 'It is snowing... Master, are your hands cold?'],


    // ---- Berry: all engine
    '主人早安！今天也要全力衝刺！': ['ご主人さま、おはようございます！今日も全力でいきます！', 'Morning, Master! Full speed again today!'],
    '主人！莓果已經熱身完畢，隨時可以上！': ['ご主人さま！ベリー、準備運動ばっちりです！', 'Master! Berry is warmed up and ready to go!'],
    '嘿嘿，主人來啦～今天要打倒幾隻灰塵？': ['えへへ、ご主人さま～今日はホコリを何匹やっつけます？', 'Hehe, Master~ How many dust bunnies are we taking down today?'],
    '欸嘿嘿……被摸頭了～力量湧上來了！': ['えへへ…なでなでされちゃった～力がわいてきます！', 'Ehehe... a head pat~ I can feel the power coming!'],
    '櫻花在飄耶！等一下去散步好不好？': ['桜が舞ってますよ！あとでお散歩しませんか？', 'Petals everywhere! Shall we take a walk later?'],
    '打、打雷了……！沒、沒事，莓果不怕！': ['か、雷……！だ、大丈夫です、ベリーは怖くないです！', 'Th-thunder...! I-I am fine, Berry is not scared!'],

    // ---- Yoru: few words, and she enjoys your reaction
    '……夜子。從今天起，主人的一切，由我管理。': ['……夜子です。今日から、ご主人さまのすべては私が管理します。', '...Yoru. From today, everything of yours is mine to manage.'],
    '……主人。': ['……ご主人さま。', '...Master.'],
    '……來了啊。': ['……来ましたか。', '...You came.'],
    '……嗯。（點頭）': ['……ん。（こくり）', '...Mm. (a small nod)'],
    '……哼。': ['……ふん。', '...Hmph.'],
    '……可以，繼續。': ['……いい。続けて。', '...Fine. Keep going.'],
    '……這種事，只准主人做。': ['……こんなこと、ご主人さまだけです。', '...Only you are allowed to do that.'],
    '……夠了。': ['……もう十分です。', '...That is enough.'],
    '……再摸，這隻手就不還你了。': ['……まだ撫でるなら、その手は返しません。', '...Pat me again and I keep the hand.'],
    '……大膽。': ['……大胆ですね。', '...Bold of you.'],
    '……這張臉，看夠了嗎。': ['……この顔、見飽きましたか。', '...Seen enough of this face?'],
    '……下次換我戳回去。做好覺悟。': ['……次は私の番です。覚悟してください。', '...Next time it is my turn. Be ready.'],
    '……啪。力道太弱了。': ['……ぱん。弱いです。', '...Clap. Too soft.'],
    '……再一次。這次認真點。': ['……もう一度。今度は本気で。', '...Again. Mean it this time.'],
    '……！別、別碰那裡……！': ['……！そ、そこは……！', '...! N-not there...!'],
    '……唔……！這筆帳，我記下了。': ['……くっ……！この借り、覚えておきます。', '...Nngh...! I will remember this.'],
    '……主人。今晚睡覺時，小心點。': ['……ご主人さま。今夜は気をつけて眠ってください。', '...Master. Sleep lightly tonight.'],
    '……有事？': ['……何か？', '...Something?'],
    '……灰塵，都斬乾淨了。': ['……ホコリは、すべて斬りました。', '...The dust has all been cut down.'],
    '……這個房間的每個角落，我都記得。': ['……この部屋の隅々まで、覚えています。', '...I know every corner of this room.'],
    '……主人的杯子放歪了。我調好了。': ['……カップが曲がっていました。直しました。', '...Your cup was crooked. I fixed it.'],
    '……話多的人，我不擅長應付。': ['……おしゃべりな人は、苦手です。', '...I am not good with talkative people.'],
    '……看主人忙來忙去，很有趣。': ['……慌ただしいご主人さまを見るのは、面白いです。', '...Watching you rush about is entertaining.'],
    '……主人今天也在看我。……可以再看久一點。': ['……今日も見ていますね。……もっと見ていても、いいですよ。', '...You are watching me again. ...You may look longer.'],
    '……害羞的表情，不錯。': ['……照れた顔、悪くないです。', '...That embarrassed face. Not bad.'],
    '……別離開我的視線範圍。': ['……私の視界から出ないでください。', '...Do not leave my sight.'],
    '……主人是我的。這點不用討論。': ['……ご主人さまは私のものです。議論の余地はありません。', '...You are mine. That is not up for discussion.'],
    '……偶爾，我也想被誇獎。': ['……たまには、褒められたいです。', '...Once in a while, I would like to be praised.'],
    '……主人，過來。……嗯，這樣就好。': ['……ご主人さま、こちらへ。……ん、それでいいです。', '...Come here, Master. ...Mm. That will do.'],
    '……要是逃跑，我會去追。': ['……逃げたら、追いかけます。', '...Run, and I will come after you.'],
    '……今天，說太多了。': ['……今日は、喋りすぎました。', '...I have said too much today.'],
    '……抹茶。……算你識相。': ['……抹茶。……気が利きますね。', '...Matcha. ...You know what you are doing.'],
    '……收下了。': ['……受け取ります。', '...I will take it.'],
    '……今天夠了。剩下的，明天再給。': ['……今日はもう十分です。続きは明日に。', '...Enough for today. The rest tomorrow.'],
    '……溫度剛好。……我可沒說謝謝。': ['……温度はちょうどいい。……お礼は言っていませんよ。', '...The temperature is right. ...I did not say thank you.'],
    '……有點累。……不准笑。': ['……少し疲れました。……笑わないでください。', '...A little tired. ...Do not laugh.'],
    '……開始。別眨眼。': ['……始めます。瞬きしないで。', '...Beginning. Do not blink.'],
    '……還不夠。': ['……まだ足りません。', '...Still not enough.'],
    '……去了。': ['……行ってきます。', '...Going.'],
    '……結束了。無聊。': ['……終わりました。退屈です。', '...Done. Dull.'],
    '……失手了。……別安慰我。': ['……しくじりました。……慰めないでください。', '...I slipped. ...Do not comfort me.'],
    '……晚安。……別做奇怪的夢。': ['……おやすみなさい。……変な夢は見ないように。', '...Good night. ...No strange dreams.'],
    '……主人，你已經逃不掉了。': ['……ご主人さま、もう逃げられませんよ。', '...Master. You cannot get away now.'],
    '……只會這一首。……別笑。': ['……弾けるのはこれだけです。……笑わないで。', '...This is the only song I can play. ...Do not laugh.'],
    '……早。': ['……おはよう。', '...Morning.'],
    '……午安。……吃飯了嗎。': ['……こんにちは。……食事は？', '...Afternoon. ...Have you eaten?'],
    '……天黑了。……我的時間。': ['……日が暮れました。……私の時間です。', '...It is dark. ...My hours.'],
    '……還醒著？……陪我一下。': ['……まだ起きてる？……少し付き合って。', '...Still awake? ...Stay with me a while.'],
    '……平日。街上很安靜，我喜歡。': ['……平日。街が静かで、好きです。', '...A weekday. The streets are quiet. I like it.'],
    '……假日。……今天，哪裡都別去。': ['……休日。……今日は、どこにも行かないで。', '...A day off. ...Go nowhere today.'],
    '……太陽。……太刺眼了。': ['……日差し。……眩しすぎます。', '...Sunlight. ...Too bright.'],
    '……雲很厚。……要下雨了。': ['……雲が厚い。……降りますね。', '...Thick clouds. ...Rain is coming.'],
    '……雨。……正好，適合睡覺。': ['……雨。……ちょうどいい、寝るのに。', '...Rain. ...Good weather for sleeping.'],
    '……雪。……手，冷嗎。': ['……雪。……手、冷たくないですか。', '...Snow. ...Are your hands cold?'],
    '……櫻花。……會掉在主人頭上。': ['……桜。……ご主人さまの頭に落ちますよ。', '...Petals. ...They will land in your hair.'],
    '……打雷。……怕的話，可以靠過來。': ['……雷。……怖いなら、寄ってもいいですよ。', '...Thunder. ...If you are scared, you may come closer.'],

    // ---- Honey: a sweet scatterbrain
    '主人早安～咦，現在是早上……對吧？': ['ご主人さま、おはようございます～あれ、今って朝……ですよね？', 'Morning, Master~ Wait, it is morning... right?'],
    '啊、主人！蜜糖剛剛在找主人……咦，找什麼來著？': ['あっ、ご主人さま！ハニー、さっき探して……あれ、何を探してたんだっけ？', 'Ah, Master! Honey was just looking for... um, what was I looking for?'],
    '主人主人～今天的點心是……啊，忘記放糖了。': ['ご主人さま～今日のおやつは……あっ、砂糖を入れ忘れました。', 'Master, Master~ Today’s snack is... ah, I forgot the sugar.'],
    '欸嘿嘿……舒服～': ['えへへ……気持ちいいです～', 'Ehehe... that feels nice~'],
    '呼哇……頭有點暈……啊不是，是開心！': ['ふわぁ……くらくらします……あっ、違います、うれしいんです！', 'Wawa... I feel dizzy... ah, no, I mean happy!'],
    '主人的手，聞起來有餅乾的味道……咦？': ['ご主人さまの手、クッキーのにおいがします……あれ？', 'Your hand smells like cookies... huh?'],
    '呀……頭髮會變成鳥窩啦～': ['やぁ……髪が鳥の巣になっちゃいます～', 'Waah... my hair is turning into a bird’s nest~'],
    '好、好了啦……蜜糖要暈了……': ['も、もう……ハニー、くらくらします……', 'Th-that is enough... Honey is getting dizzy...'],
    '呀！……咦，剛剛是誰戳我？': ['きゃっ！……あれ、今つついたの誰ですか？', 'Eep! ...Huh, who poked me just now?'],
    '嘿嘿，臉頰軟軟的對吧？': ['えへへ、ほっぺ、ふわふわでしょう？', 'Hehe, my cheek is squishy, right?'],
    '主、主人……再戳下去，蜜糖要哭了喔？': ['ご、ご主人さま……これ以上つついたら、ハニー泣いちゃいますよ？', 'M-Master... poke me again and Honey is going to cry, okay?'],
    '耶～擊掌♪……啊，打歪了。': ['やった～ハイタッチ♪……あっ、外れました。', 'Yay~ high five♪ ...Ah, I missed.'],
    '嘿嘿，手掌好燙喔～': ['えへへ、手のひらが熱いです～', 'Hehe, my palm is all warm~'],
    '呀哈哈！住手～會、會打翻東西的！': ['やははっ！やめて～な、何か倒しちゃいます！', 'Ahaha! Stop~ I-I am going to knock something over!'],
    '哈哈哈！不、不行啦主人～': ['ははは！だ、だめですご主人さま～', 'Hahaha! N-no, Master~'],
    '呼……呼……蜜糖的腦袋，已經變成棉花糖了……': ['はぁ……はぁ……ハニーの頭、綿あめになっちゃいました……', 'Haah... haah... Honey’s head has turned into cotton candy...'],
    '今天的鬆餅……咦，我烤了嗎？': ['今日のパンケーキ……あれ、焼きましたっけ？', 'Today’s pancakes... wait, did I bake them?'],
    '砂糖和鹽長得好像喔，主人覺得呢？': ['お砂糖とお塩って似てますよね、ご主人さまもそう思いません？', 'Sugar and salt look so alike, don’t you think?'],
    '蜜糖最喜歡烤點心了♪': ['ハニー、お菓子を焼くのが大好きです♪', 'Honey loves baking sweets♪'],
    '啊、主人的杯子，我洗過了……應該吧？': ['あっ、ご主人さまのカップ、洗いました……たぶん？', 'Ah, I washed your cup... probably?'],
    '小兔子今天也很有精神喔～': ['うさぎさん、今日も元気ですよ～', 'The bunny is full of beans today too~'],
    '跟主人在一起，就會忘記時間呢。': ['ご主人さまといると、時間を忘れちゃいます。', 'With you I lose track of time.'],
    '主人愛吃甜的嗎？蜜糖記起來了！': ['ご主人さまは甘いもの好きですか？ハニー、覚えました！', 'Do you like sweet things? Honey will remember!'],
    '欸嘿嘿，剛剛在想主人的事，結果糖放了兩次。': ['えへへ、ご主人さまのことを考えてたら、お砂糖を二回入れちゃいました。', 'Ehehe, I was thinking about you and put the sugar in twice.'],
    '主人笑起來的樣子，蜜糖最喜歡了。': ['笑っているご主人さまが、ハニーは一番好きです。', 'Honey likes your smile best of all.'],
    '主人，今天也留在蜜糖身邊嘛～': ['ご主人さま、今日もハニーのそばにいてください～', 'Master, stay by Honey today too~'],
    '啊……剛剛想說什麼來著？……嗯，喜歡主人！': ['あっ……何を言おうとしてたっけ？……えっと、ご主人さまが好きです！', 'Ah... what was I about to say? ...Um, I like you!'],
    '主人是蜜糖的第一名喔♪': ['ご主人さまはハニーの一番です♪', 'You are Honey’s number one♪'],
    '欸嘿嘿……牽手可以嗎？': ['えへへ……手、つないでもいいですか？', 'Ehehe... may I hold your hand?'],
    '呼哇～聊到頭昏了，剩下的明天再說吧♪': ['ふわぁ～お話しすぎて目が回りました。続きは明日に♪', 'Wawa~ I have talked myself dizzy. The rest tomorrow♪'],
    '蜂蜜蛋糕！主人怎麼知道……啊，我說過好幾次了對吧♪': ['はちみつケーキ！どうして分かったんですか……あっ、何回も言ってましたね♪', 'Honey cake! How did you know... ah, I have said it a dozen times♪'],
    '謝謝主人～蜜糖會好好收著的！': ['ありがとうございます～ハニー、大事にします！', 'Thank you~ Honey will take good care of it!'],
    '今天收好多禮物……咦，剛剛那個放哪去了？': ['今日はプレゼントがいっぱい……あれ、さっきのどこに置いたっけ？', 'So many presents today... huh, where did I put that one?'],
    '啊、砂糖放了兩次……主人，這杯會很甜喔？': ['あっ、お砂糖を二回入れちゃいました……ご主人さま、甘いですよ？', 'Ah, I added the sugar twice... this one is going to be sweet, okay?'],
    '呼哇……主人，蜜糖的腳站不太住了……': ['ふわぁ……ご主人さま、ハニーの足、ふらふらします……', 'Wawa... Master, Honey’s legs are wobbling...'],
    '特訓……咦，今天是要練什麼來著？': ['特訓……あれ、今日は何をするんでしたっけ？', 'Training... um, what were we training today?'],
    '呼～流了好多汗！……啊，鬆餅忘在烤箱裡了！': ['ふぅ～いい汗かきました！……あっ、パンケーキをオーブンに忘れてます！', 'Phew~ what a workout! ...Ah, I left the pancakes in the oven!'],
    '蜜糖出發囉～啊、鑰匙，鑰匙帶了嗎？': ['ハニー、行ってきます～あっ、鍵、鍵は持ちましたっけ？', 'Honey is off~ ah, keys, did I bring the keys?'],
    '我回來了～欸嘿嘿，路上迷了一下下路。': ['ただいまです～えへへ、ちょっとだけ迷いました。', 'I am back~ ehehe, I got a teeny bit lost.'],
    '啊、花瓣掉進紅茶裡了……這樣也很香吧？': ['あっ、花びらが紅茶に落ちました……これはこれで、いい香りですよね？', 'Ah, a petal fell in the tea... that smells lovely too, right?'],
    '呀！打、打雷了……蜜糖可以躲在主人後面嗎？': ['きゃっ！か、雷……ハニー、ご主人さまの後ろに隠れてもいいですか？', 'Eep! Th-thunder... may Honey hide behind you?'],

    // ---- Yukino: the big sister
    '我是雪乃。年紀比大家都大一點，就讓姊姊來照顧主人吧。': ['ユキノです。みんなより少し年上ですから、お姉さんがご主人さまのお世話をしますね。', 'I am Yukino. I am the oldest here, so let your big sister look after you.'],
    '主人，早安。姊姊等你很久囉。': ['ご主人さま、おはようございます。お姉さん、待っていましたよ。', 'Good morning, Master. Your big sister has been waiting.'],
    '呵呵，主人來了。今天想做什麼呢？': ['ふふ、ご主人さま。今日は何をしましょうか？', 'Hehe, there you are. What shall we do today?'],
    '慢慢來就好，姊姊會陪著你。': ['ゆっくりで大丈夫。お姉さんがついています。', 'Take your time. I am right here.'],
    '呵呵……被主人摸頭，感覺很新鮮呢。': ['ふふ……ご主人さまに撫でられるのは、新鮮ですね。', 'Hehe... being patted by you is rather novel.'],
    '好乖好乖……啊，反過來了。': ['よしよし……あら、逆ですね。', 'There, there... ah, we have it backwards.'],
    '真是的，主人也太會撒嬌了。': ['もう、ご主人さまは甘え上手ですね。', 'Honestly, you are far too good at being spoiled.'],
    '好了好了，頭髮會亂掉喔。': ['はいはい、髪が乱れてしまいますよ。', 'All right, all right, you will muss my hair.'],
    '呵呵，撒嬌也要適可而止呢。': ['ふふ、甘えるのもほどほどに。', 'Hehe, there is a limit to spoiling, you know.'],
    '呀……真是的，主人。': ['きゃっ……もう、ご主人さま。', 'Ah... really, Master.'],
    '呵呵，戳姊姊的臉頰很好玩嗎？': ['ふふ、お姉さんのほっぺ、そんなに楽しいですか？', 'Hehe, is poking your big sister’s cheek that fun?'],
    '再鬧下去，姊姊可要處罰你囉？': ['これ以上いたずらすると、お姉さん、お仕置きしますよ？', 'Any more mischief and your big sister will have to punish you.'],
    '來，擊掌。做得很好喔。': ['はい、ハイタッチ。よくできました。', 'There, a high five. Well done.'],
    '呵呵，配合得真好。': ['ふふ、息がぴったりですね。', 'Hehe, we are well in step.'],
    '呀……！主、主人，太犯規了……': ['きゃっ……！ご、ご主人さま、それは反則です……', 'Ah...! M-Master, that is cheating...'],
    '哈哈……！等、等一下……！': ['ははっ……！ま、待って……！', 'Haha...! W-wait a moment...!'],
    '呼……真是的。姊姊也是會怕癢的。': ['はぁ……もう。お姉さんだってくすぐったいんですよ。', 'Phew... really. Your big sister is ticklish too.'],
    '主人的書桌，姊姊幫你整理好了。': ['ご主人さまの机、お姉さんが片づけておきました。', 'I tidied your desk for you.'],
    '眼鏡嗎？只是看書用的，度數其實很淺。': ['眼鏡ですか？読書用ですよ。度は弱いんです。', 'My glasses? Only for reading. The lenses are weak.'],
    '有什麼煩惱，都可以跟姊姊說喔。': ['悩みがあれば、お姉さんに話してくださいね。', 'If something is troubling you, tell your big sister.'],
    '主人，今天有好好吃飯嗎？': ['ご主人さま、今日はちゃんと食べましたか？', 'Master, did you eat properly today?'],
    '呵呵，看著主人努力的樣子，姊姊很開心。': ['ふふ、頑張るご主人さまを見ていると、お姉さんは嬉しいです。', 'Hehe, seeing you work hard makes me happy.'],
    '要不要靠著休息一下？肩膀借你。': ['少し寄りかかって休みませんか？肩、貸しますよ。', 'Care to lean on me a while? You may borrow my shoulder.'],
    '主人偶爾也可以任性一點喔。': ['ご主人さまも、たまにはわがままでいいんですよ。', 'You may be selfish once in a while, you know.'],
    '這種粗活，讓姊姊來就好。': ['こういう力仕事は、お姉さんに任せてください。', 'Leave the heavy work to your big sister.'],
    '……被主人依賴的感覺，其實不壞呢。': ['……ご主人さまに頼られるのは、悪くないですね。', '...Being relied on by you is not bad at all.'],
    '主人，今天也讓姊姊多疼你一點吧？': ['ご主人さま、今日ももう少し甘やかしてもいいですか？', 'Master, may I spoil you a little more today?'],
    '……真是的，明明是主人，卻讓人想寵著。': ['……もう。ご主人さまなのに、甘やかしたくなります。', '...Honestly. You are the master, yet you make me want to pamper you.'],
    '主人的第一名，姊姊可不會讓給別人喔。': ['ご主人さまの一番は、誰にも譲りませんよ。', 'I am not giving up first place with you to anyone.'],
    '……呵呵，姊姊也是會吃醋的。': ['……ふふ、お姉さんだって妬くんですよ。', '...Hehe, your big sister gets jealous too.'],
    '今天聊得很開心呢。剩下的留到明天吧。': ['今日は楽しくお話しできました。続きは明日にしましょう。', 'We had a lovely talk today. Let us save the rest for tomorrow.'],
    '冰淇淋……！呵呵，主人真懂姊姊。': ['アイスクリーム……！ふふ、ご主人さまは分かっていますね。', 'Ice cream...! Hehe, you know me well.'],
    '謝謝主人。姊姊會好好收下的。': ['ありがとうございます。お姉さん、大事にいただきますね。', 'Thank you. Your big sister will treasure it.'],
    '呵呵，今天已經收很多了。留一些到明天吧。': ['ふふ、今日はもうたくさん頂きました。残りは明日に。', 'Hehe, I have received plenty today. Save the rest for tomorrow.'],
    '紅茶泡好了。來，小心燙。': ['紅茶が入りましたよ。はい、熱いので気をつけて。', 'The tea is ready. Here — careful, it is hot.'],
    '……抱歉，姊姊也有點累了呢。': ['……ごめんなさい、お姉さんも少し疲れました。', '...Sorry, even your big sister is a little tired.'],
    '好，開始吧。姊姊會看著你的。': ['さあ、始めましょう。お姉さんが見ていますよ。', 'Right, let us begin. I will be watching.'],
    '呵呵，表現得很好喔。': ['ふふ、よくできました。', 'Hehe, very well done.'],
    '那麼，姊姊出門囉。': ['それでは、お姉さん、行ってきますね。', 'Well then, your big sister is off.'],
    '我回來了。有沒有乖乖等姊姊呀？': ['ただいま。いい子で待っていましたか？', 'I am home. Were you good while I was out?'],
    '……抱歉，姊姊失手了。下次會補回來的。': ['……ごめんなさい、しくじりました。次で取り返します。', '...Sorry, I slipped up. I will make it up next time.'],
    '晚安，主人。做個好夢喔。': ['おやすみなさい、ご主人さま。いい夢を。', 'Good night, Master. Sweet dreams.'],
    '呵呵……主人越來越離不開姊姊了呢。': ['ふふ……ご主人さま、お姉さんから離れられなくなってきましたね。', 'Hehe... you are growing rather attached to your big sister.'],
    '這首曲子，是姊姊以前最常彈的。': ['この曲、お姉さんが昔よく弾いていたんですよ。', 'I used to play this piece all the time.'],
    '主人，早安。有睡飽嗎？': ['ご主人さま、おはようございます。よく眠れましたか？', 'Good morning, Master. Did you sleep well?'],
    '午安，主人。午餐吃了嗎？': ['こんにちは、ご主人さま。お昼は食べましたか？', 'Good afternoon, Master. Have you had lunch?'],
    '傍晚了呢。今天辛苦了，來，坐下休息。': ['夕方ですね。今日もお疲れさま。さあ、座って休んで。', 'Evening already. Good work today — come, sit and rest.'],
    '這麼晚還不睡？……真拿你沒辦法。': ['こんな時間まで起きて？……仕方のない人ですね。', 'Still up at this hour? ...What am I to do with you.'],
    '平日也要好好照顧自己喔，主人。': ['平日もちゃんと自分を大事にしてくださいね、ご主人さま。', 'Look after yourself on weekdays too, Master.'],
    '今天是假日呢。要不要讓姊姊陪你放鬆一下？': ['今日はお休みですね。お姉さんとのんびりしませんか？', 'A day off today. Shall we take it easy together?'],
    '天氣真好。要不要一起去曬棉被？': ['いいお天気。一緒にお布団を干しませんか？', 'Lovely weather. Shall we air the futons together?'],
    '有點陰呢。出門記得帶件外套。': ['少し曇っていますね。お出かけには上着を。', 'A bit overcast. Take a jacket if you go out.'],
    '下雨了。……主人，有沒有淋濕？': ['雨ですね。……ご主人さま、濡れていませんか？', 'It is raining. ...Did you get wet, Master?'],
    '下雪了呢。手伸過來，姊姊幫你暖暖。': ['雪ですね。手を出して、お姉さんが温めてあげます。', 'Snow. Give me your hands, I will warm them.'],
    '櫻花開了呢。等等去走走好嗎？': ['桜が咲きましたね。あとでお散歩しませんか？', 'The blossoms are out. Shall we walk later?'],
    '打雷了。……怕的話，可以靠過來喔。': ['雷ですね。……怖かったら、寄ってきていいですよ。', 'Thunder. ...If you are frightened, come closer.'],
    // ---- gifts that each do something, and what the maids say about them
    '運動飲料': ['スポーツドリンク', 'Sports Drink'],
    '推理小說': ['ミステリー小説', 'Mystery Novel'],
    '幸運御守': ['幸運のお守り', 'Lucky Charm'],
    '體力 +20': ['体力 +20', '+20 STA'],
    '體力 +10・心情 +10': ['体力 +10・気分 +10', '+10 STA, +10 Mood'],
    '心情 +25': ['気分 +25', '+25 Mood'],
    '心情 +10・家事經驗 +15': ['気分 +10・家事EXP +15', '+10 Mood, +15 Chores EXP'],
    '體力 +50': ['体力 +50', '+50 STA'],
    '爆破研究經驗 +25': ['ボム研究EXP +25', '+25 Bomb Lab EXP'],
    '下次委託免死一次': ['次の依頼で復活1回', 'Next job: 1 revive'],
    '好感 +15・心情全滿': ['好感度 +15・気分MAX', '+15 Affection, full Mood'],
    '好感 +32': ['好感度 +32', '+32 Affection'],
    '{gift}！好耶——謝謝主人，莓果收下了！': ['{gift}！やったー！ありがとうございます、ベリーがもらいますっ！', '{gift}! Yay! Thank you, Master, Berry will take it!'],
    '字、字好多……莓果看了頭會暈啦……不過我會努力讀讀看！': ['じ、字がいっぱい……ベリー、目が回っちゃう……でも、がんばって読んでみます！', "S-so many words... Berry's head is spinning... but I'll try to read it!"],
    '力氣全部回來了！現在就能出擊！': ['力が全部戻ってきた！今すぐ出撃できます！', 'All my strength is back! I can head out right now!'],
    '嘿嘿，心情超好的！': ['えへへ、気分サイコーです！', 'Hehe, I feel amazing!'],
    '唔……好像學到了什麼！': ['うーん……なにか覚えた気がします！', 'Hmm... I think I learned something!'],
    '有這個在，下次委託莓果一定贏！': ['これがあれば、次の依頼はベリーの勝ちです！', 'With this, Berry wins the next job for sure!'],
    '哇～{gift}！……咦，真的是給蜜糖的嗎？': ['わぁ～{gift}！……あれ、ほんとにハニーにですか？', 'Wow~ {gift}! ...Huh, is it really for Honey?'],
    '苦、苦苦的……蜜糖會加油吃完的……嗚。': ['に、にがい……ハニー、がんばって食べます……うぅ。', 'B-bitter... Honey will do her best to finish it... ugh.'],
    '好像……充滿電了？蜜糖現在超有精神！': ['なんだか……充電できた？ハニー、今すっごく元気です！', 'I feel... charged up? Honey is full of energy now!'],
    '欸嘿嘿～好幸福喔～': ['えへへ～しあわせです～', 'Ehehe~ So happy~'],
    '學、學到了……吧？欸嘿嘿。': ['お、覚えた……かな？えへへ。', 'I-I learned it... I think? Ehehe.'],
    '要好好收著……先放口袋……咦，哪個口袋？': ['大事にしまって……ポケットに……あれ、どのポケット？', "I'll keep it safe... in my pocket... huh, which pocket?"],
    '呵呵，{gift}呀。主人的品味不錯呢。': ['ふふ、{gift}ですか。いいセンスですね、ご主人さま。', 'Hehe, {gift}. You have good taste, Master.'],
    '呵呵……姊姊不需要這麼有活力喔。不過，謝謝你。': ['ふふ……お姉さんはそんなに元気いっぱいじゃなくていいんですよ。でも、ありがとう。', "Hehe... your big sister doesn't need that much pep. But thank you."],
    '精神好多了。主人也別太勉強自己喔。': ['だいぶ元気が出ました。ご主人さまも無理しないでくださいね。', "I feel much better. Don't push yourself too hard either, Master."],
    '呵呵，今天會是很好的一天呢。': ['ふふ、今日はいい一日になりそうですね。', "Hehe, today's going to be a lovely day."],
    '原來如此，又學到一課了。': ['なるほど、また一つ勉強になりました。', 'I see. Another lesson learned.'],
    '下次委託，姊姊會帶著它。……也帶著主人的心意。': ['次の依頼には、これを持っていきます。……ご主人さまの気持ちも一緒に。', "I'll take it on the next job. ...Along with your feelings, Master."],
    '……{gift}。……還行。': ['……{gift}。……悪くないです。', '...{gift}. ...Not bad.'],
    '……太甜了。……不過，吃完了。': ['……甘すぎます。……でも、食べました。', '...Too sweet. ...I ate it all, though.'],
    '……蕾絲？這種東西，不適合我。': ['……レース？こういうのは、私には似合いません。', "...Lace? That sort of thing doesn't suit me."],
    '……明天，戴給你看。': ['……明日、つけてみせます。', "...Tomorrow. I'll wear it for you."],
    '……嗯。可以再陪你一會。': ['……ん。もう少し付き合えます。', '...Mm. I can keep you company a while longer.'],
    '……哼。還不錯。': ['……ふん。まあまあです。', '...Hmph. Decent.'],
    '……記住了。': ['……覚えました。', '...Memorized.'],
    '……我不需要保護。……不過，收下了。': ['……守られる必要はありません。……でも、もらっておきます。', "...I don't need protecting. ...But I'll keep it."],
    // ---- touches that grow with affection (shy at first, close once she loves you)
    '欸？摸、摸頭？……主人突然這樣，莓果會嚇一跳的啦！': ['えっ？な、なでなで？……いきなりだとベリーびっくりしちゃいますよ！', 'Huh? A-a head pat? ...Do that out of nowhere and Berry jumps!'],
    '唔……還不太習慣，不過不討厭喔！': ['うーん……まだ慣れないけど、イヤじゃないです！', 'Mm... not used to it yet, but I don\'t hate it!'],
    '嘿嘿～主人的手最棒了！再多摸一點！': ['えへへ～ご主人さまの手、最高です！もっとなでて！', 'Hehe~ Your hands are the best, Master! More!'],
    '被主人摸頭，莓果就充滿力量了！最喜歡了！': ['ご主人さまになでられると、ベリー元気百倍です！大好き！', 'One pat from you and Berry\'s power is maxed! Love you!'],
    '呀！主人，偷襲犯規！': ['ひゃっ！ご主人さま、不意打ちは反則です！', 'Eek! Master, sneak attacks are against the rules!'],
    '戳、戳臉頰？主人好奇怪喔！': ['ほ、ほっぺつんつん？ご主人さま、変なの！', 'P-poking my cheek? Master, you\'re so weird!'],
    '嘿嘿，戳回去！……開玩笑的啦～': ['えへへ、つつき返し！……なーんてね～', 'Hehe, poke back! ...Just kidding~'],
    '主人想要莓果看你嗎？莓果一直都在看你喔！': ['ご主人さま、ベリーに見てほしいんですか？ずっと見てますよ！', 'Want Berry to look at you? I\'m always looking at you!'],
    '擊、擊掌？好！耶！': ['ハ、ハイタッチ？はいっ！イェイ！', 'H-high five? Okay! Yay!'],
    '這樣就是搭檔了嗎？好，莓果會加油！': ['これで相棒ですか？よーし、ベリーがんばります！', 'Does this make us partners? Okay, Berry will do her best!'],
    '耶——！我們是最強的搭檔！永遠都是！': ['イェーイ！わたしたち最強の相棒です！ずっとずっと！', 'Yeeeah! We\'re the strongest partners! Forever!'],
    '跟主人擊掌，什麼委託都不怕了！': ['ご主人さまとハイタッチしたら、どんな依頼もこわくない！', 'After a high five with you, no job can scare me!'],
    '哇哈哈！住、住手啦！': ['あはは！や、やめてください～！', 'Wahaha! S-stop it!'],
    '主人！這樣很犯規耶！哈哈！': ['ご主人さま！それ反則です！あははっ！', 'Master! That\'s cheating! Haha!'],
    '哈哈哈！好啦好啦，主人最壞了～': ['あははっ！わかりました、ご主人さまのいじわる～', 'Hahaha! Okay, okay, you\'re the meanest~'],
    '呀哈哈！莓果投降！最喜歡主人了！': ['きゃはは！ベリー降参です！ご主人さま大好き！', 'Kyahaha! Berry gives up! I love you, Master!'],
    '……別碰我。': ['……触らないでください。', '...Don\'t touch me.'],
    '……（瞪）': ['……（じろり）', '...(glare)'],
    '……嗯。可以再一下。': ['……ん。もう少しなら、いいです。', '...Mm. A little longer is fine.'],
    '……只有主人，可以。': ['……ご主人さまだけ、特別です。', '...Only you, Master.'],
    '……再戳，就砍了。': ['……もう一度つついたら、斬ります。', '...Poke again and I cut.'],
    '……無聊。': ['……くだらない。', '...Pointless.'],
    '……主人，很閒嗎。……那就陪你。': ['……ご主人さま、暇なんですか。……なら付き合います。', '...Are you bored, Master. ...Then I\'ll keep you company.'],
    '……（戳回去）……扯平了。': ['……（つつき返す）……おあいこです。', '...(pokes back) ...Even.'],
    '……擊掌？……哼。': ['……ハイタッチ？……ふん。', '...A high five? ...Hmph.'],
    '……勉強配合你。': ['……仕方なく、合わせます。', '...I\'ll go along. Barely.'],
    '……嗯。今天也，辛苦了。': ['……ん。今日も、お疲れさまです。', '...Mm. Good work today, too.'],
    '……主人的手，很暖。': ['……ご主人さまの手、あたたかいです。', '...Your hand is warm, Master.'],
    '……住手。……唔、……住手。': ['……やめて。……っ、……やめてください。', '...Stop. ...Nn, ...stop.'],
    '……（忍住）……': ['……（こらえる）……', '...(holding it in)...'],
    '……噗。……剛才，什麼都沒發生。': ['……ぷっ。……今のは、何もなかったことに。', '...Pfft. ...That never happened.'],
    '……主人，犯規。……哈、……哈哈。': ['……ご主人さま、反則です。……は、……はは。', '...Master, that\'s cheating. ...Ha, ...haha.'],
    '咦？頭上有什麼東西嗎？……啊，是主人的手！': ['あれ？頭に何か……あっ、ご主人さまの手でした！', 'Huh? Something on my head? ...Oh, it\'s your hand!'],
    '欸嘿……有點不好意思呢……': ['えへ……ちょっと恥ずかしいです……', 'Ehe... that\'s a little embarrassing...'],
    '欸嘿嘿～主人摸頭好舒服……蜜糖要睡著了……': ['えへへ～ご主人さまのなでなで、気持ちいい……ハニー、眠くなっちゃう……', 'Ehehe~ Your head pats feel so nice... Honey\'s getting sleepy...'],
    '再摸一下下嘛～蜜糖最喜歡主人了～': ['もうちょっとだけ～ハニー、ご主人さま大好きです～', 'Just a little more~ Honey loves you, Master~'],
    '呀？臉、臉頰怎麼了嗎？': ['ひゃ？ほ、ほっぺがどうかしました？', 'Eep? Is s-something wrong with my cheek?'],
    '咦？蜜糖臉上沾到東西了嗎？': ['あれ？ハニーのお顔に何かついてます？', 'Huh? Does Honey have something on her face?'],
    '唔～主人壞壞，蜜糖也要戳回去！': ['むぅ～ご主人さまのいじわる、ハニーもつつき返します！', 'Mmm~ Meanie, Honey\'s poking you back!'],
    '欸嘿嘿，被主人戳了～好開心～': ['えへへ、ご主人さまにつつかれちゃった～うれしいです～', 'Ehehe, you poked me~ That makes me happy~'],
    '擊、擊掌？啊，手舉錯邊了……': ['ハ、ハイタッチ？あっ、手が逆でした……', 'H-high five? Oh, wrong hand...'],
    '耶……？這樣對嗎？': ['イェ……？これで合ってます？', 'Yay...? Is this right?'],
    '耶～！跟主人擊掌，今天也會很順利喔～': ['イェ～い！ご主人さまとハイタッチ、今日もうまくいきますね～', 'Yay~! A high five with you, today will go great too~'],
    '啪！欸嘿嘿，蜜糖這次有對準了！': ['パチン！えへへ、ハニー今度はちゃんと当たりました！', 'Clap! Ehehe, Honey hit it right this time!'],
    '呀哈哈！好、好癢！不要啦～': ['きゃはは！く、くすぐったい！やめて～', 'Kyahaha! T-that tickles! Stop~'],
    '哇、哇啊！蜜糖會跌倒的！': ['わ、わわっ！ハニー転んじゃいます！', 'W-waah! Honey\'s going to fall over!'],
    '欸嘿嘿嘿～主人好壞～蜜糖要生氣了喔～（沒有生氣）': ['えへへへ～ご主人さまのいじわる～ハニー怒っちゃいますよ～（怒ってない）', 'Ehehehe~ You\'re so mean~ Honey\'s getting angry~ (she isn\'t)'],
    '哈哈哈～好癢好癢～最喜歡主人了～': ['あはは～くすぐったい～ご主人さま大好き～', 'Hahaha~ So ticklish~ I love you, Master~'],
    '……主人？被摸頭有點意外呢。': ['……ご主人さま？なでられるなんて、ちょっと意外ですね。', '...Master? A head pat, how unexpected.'],
    '呵呵，主人對姊姊也會這樣嗎？': ['ふふ、お姉さんにもそういうことするんですか？', 'Hehe, you\'d do that even to your big sister?'],
    '呵呵……被主人摸頭，姊姊也會想撒嬌的呢。': ['ふふ……ご主人さまになでられると、お姉さんも甘えたくなっちゃいます。', 'Hehe... when you pat me like that, even your big sister wants to be spoiled.'],
    '真拿你沒辦法……只准主人喔。': ['しょうがないですね……ご主人さまだけですよ。', 'You\'re hopeless... Only you, you know.'],
    '主人，這樣很失禮喔。……呵呵，開玩笑的。': ['ご主人さま、それは失礼ですよ。……ふふ、冗談です。', 'Master, that\'s rude. ...Hehe, just teasing.'],
    '嗯？怎麼了，有話要跟姊姊說嗎？': ['ん？どうしました、お姉さんに何かお話ですか？', 'Hm? What is it, something to tell your big sister?'],
    '呵呵，主人想要姊姊多看你一點嗎？': ['ふふ、お姉さんにもっと見てほしいんですか？', 'Hehe, do you want your big sister to look at you more?'],
    '真是的……要戳的話，換姊姊戳你喔？': ['もう……つつくなら、お姉さんがつつき返しますよ？', 'Honestly... if you poke me, I\'ll poke you back, you know?'],
    '擊掌嗎？好的，辛苦了。': ['ハイタッチですか？はい、お疲れさまです。', 'A high five? Of course. Good work.'],
    '呵呵，很有精神呢，主人。': ['ふふ、元気いっぱいですね、ご主人さま。', 'Hehe, you\'re full of energy, Master.'],
    '辛苦了，我最可靠的主人。': ['お疲れさまです、わたしの一番頼れるご主人さま。', 'Good work, my most dependable Master.'],
    '呵呵，下次也一起努力吧。姊姊一直都在。': ['ふふ、次も一緒にがんばりましょう。お姉さんはずっとそばにいますから。', 'Hehe, let\'s do our best next time too. Your big sister is always here.'],
    '等、等一下……主人！呵、呵呵……': ['ま、待って……ご主人さま！ふ、ふふっ……', 'W-wait... Master! Heh, hehe...'],
    '這種事……不、不行……哈哈！': ['そ、そういうのは……だ、だめ……あはは！', 'T-that kind of thing... n-no... haha!'],
    '哈哈……主人真是的，姊姊要反擊了喔？': ['あはは……もう、ご主人さまったら。お姉さん、反撃しちゃいますよ？', 'Haha... honestly, Master. Your big sister is going to strike back, you know?'],
    '呵、呵呵……好啦好啦，姊姊投降。': ['ふ、ふふ……はいはい、お姉さんの負けです。', 'Heh, hehe... all right, all right, your big sister surrenders.'],
    // ---- what grows with affection: hand in hand, photos, hugs, whispers, her questions, more talk
    '牽、牽手？……好、好啊！莓果帶路！': ['て、手をつなぐんですか？……い、いいですよ！ベリーが案内します！', 'H-hold hands? ...O-okay! Berry will lead the way!'],
    '主人的手好大喔……有點緊張耶。': ['ご主人さまの手、大きいですね……ちょっと緊張します。', 'Your hand is so big, Master... I\'m a little nervous.'],
    '嘿嘿，一起散步！主人要跟上喔！': ['えへへ、一緒にお散歩！ご主人さま、ついてきてくださいね！', 'Hehe, a walk together! Keep up, Master!'],
    '牽著手走，房間好像變大了呢！': ['手をつないで歩くと、お部屋が広く感じますね！', 'Walking hand in hand, the room feels bigger!'],
    '不放開喔！今天一整天都不放開！': ['離しませんよ！今日は一日中離しません！', 'I\'m not letting go! Not all day!'],
    '跟主人牽手走路，是莓果最喜歡的事！': ['ご主人さまと手をつないで歩くの、ベリーの一番好きなことです！', 'Walking hand in hand with you is Berry\'s favorite thing!'],
    '耶！V！拍得帥一點喔！': ['イェイ！ピース！かっこよく撮ってくださいね！', 'Yay! Peace sign! Make me look cool!'],
    '再一張！這次莓果要跳起來拍！': ['もう一枚！今度はベリー、ジャンプして撮ります！', 'One more! This time Berry\'s jumping!'],
    '要跟主人的照片放在一起喔！': ['ご主人さまの写真と一緒に飾ってくださいね！', 'Put it right next to your photo, okay?'],
    '嘿嘿，這張要當成寶物！': ['えへへ、この一枚は宝物にします！', 'Hehe, this one\'s going to be my treasure!'],
    '抱——！嘿嘿，莓果的力氣很大喔，要抱緊囉！': ['ぎゅーっ！えへへ、ベリー力持ちですから、しっかりつかまっててください！', 'Squeeeze! Hehe, Berry\'s strong, so hold on tight!'],
    '主人好溫暖……再、再一下下就好……': ['ご主人さま、あったかい……も、もうちょっとだけ……', 'You\'re so warm, Master... j-just a little longer...'],
    '充電完畢！現在什麼都做得到！': ['充電完了！今なら何でもできます！', 'Fully charged! I can do anything now!'],
    '主人，靠過來一點……（小聲）': ['ご主人さま、もうちょっと近くに……（小声）', 'Master, come a little closer... (whispering)'],
    '其實……莓果最想保護的，不是委託，是主人。': ['本当は……ベリーが一番守りたいのは、依頼じゃなくてご主人さまなんです。', 'The truth is... what Berry wants to protect most isn\'t the job. It\'s you.'],
    '打雷的晚上，只要想到主人，就不怕了喔。': ['雷の夜も、ご主人さまのことを考えたら、こわくなくなるんです。', 'Even on thunder nights, if I think of you, I\'m not scared anymore.'],
    '這是秘密……莓果以後也想一直當主人的女僕。': ['秘密ですよ……ベリー、これからもずっとご主人さまのメイドでいたいです。', 'It\'s a secret... Berry wants to be your maid forever.'],
    '欸？那個……等我們再熟一點啦！': ['えっ？それは……もうちょっと仲良くなってからです！', 'Huh? That\'s... once we\'re a bit closer!'],
    '主人！等你好久了！今天也要一直在一起喔！': ['ご主人さま！ずっと待ってました！今日も一緒にいてくださいね！', 'Master! I\'ve been waiting forever! Stay with me today too!'],
    '主人來了！莓果的元氣全開了！': ['ご主人さまが来た！ベリー、元気全開です！', 'You\'re here! Berry\'s energy is at full blast!'],
    '主人主人！陪莓果玩嘛！': ['ご主人さま、ご主人さま！ベリーと遊んでください！', 'Master, Master! Play with Berry!'],
    '主人，摸摸頭！……不行嗎？': ['ご主人さま、なでなでして！……だめですか？', 'Master, head pats! ...No?'],
    '嘿嘿，就是在等這個！': ['えへへ、これを待ってたんです！', 'Hehe, this is what I was waiting for!'],
    '主人！草莓跟巧克力，你比較喜歡哪個？': ['ご主人さま！いちごとチョコ、どっちが好きですか？', 'Master! Strawberries or chocolate, which do you like more?'],
    '草莓': ['いちご', 'Strawberries'],
    '對吧對吧！莓果就知道主人最懂了！': ['ですよね！ご主人さまならわかってくれると思ってました！', 'Right?! I knew you\'d get it, Master!'],
    '巧克力': ['チョコ', 'Chocolate'],
    '唔……那莓果就做草莓巧克力！兩個都有！': ['むぅ……じゃあベリー、いちごチョコを作ります！両方です！', 'Mm... then Berry will make strawberry chocolate! Both at once!'],
    '如果莓果跟灰塵怪物打起來，主人會幫誰加油？': ['もしベリーとホコリの怪物が戦ったら、ご主人さまはどっちを応援しますか？', 'If Berry fought a dust monster, who would you cheer for?'],
    '當然是莓果': ['もちろんベリー', 'Berry, of course'],
    '嘿嘿！有主人加油，莓果一百倍強！': ['えへへ！ご主人さまの応援があれば、ベリー百倍強いです！', 'Hehe! With you cheering, Berry\'s a hundred times stronger!'],
    '灰塵怪物': ['ホコリの怪物', 'The dust monster'],
    '欸——！主人好過分！莓果要哭了喔！……騙你的！': ['えーっ！ご主人さまひどい！ベリー泣いちゃいますよ！……うそです！', 'Whaaat! That\'s mean, Master! Berry\'s gonna cry! ...Just kidding!'],
    '主人，休假的時候想做什麼？': ['ご主人さま、お休みの日は何がしたいですか？', 'Master, what do you want to do on your day off?'],
    '一起出去玩': ['一緒に出かけたい', 'Go out together'],
    '好耶！去公園跑步，然後吃可麗餅！': ['やったー！公園を走って、それからクレープです！', 'Yay! A run in the park, then crêpes!'],
    '在家睡覺': ['家で寝ていたい', 'Sleep in at home'],
    '那莓果幫主人把被子曬得鬆鬆軟軟的！': ['じゃあベリー、お布団をふかふかに干しておきます！', 'Then Berry will air your futon till it\'s nice and fluffy!'],
    '莓果的座右銘是「一擊必殺」！打掃也是！': ['ベリーの座右の銘は「一撃必殺」です！お掃除もです！', 'Berry\'s motto is \'one hit, one win\'! Cleaning too!'],
    '主人，要不要一起晨跑？很舒服喔！': ['ご主人さま、一緒に朝ランしませんか？気持ちいいですよ！', 'Master, want to go for a morning run together? It feels great!'],
    '主人受傷的話，莓果會很難過的……要小心喔。': ['ご主人さまがケガしたら、ベリーすごく悲しいです……気をつけてくださいね。', 'If you got hurt, Berry would be so sad... Be careful, okay?'],
    '主人的手……好想再牽一次。啊，沒、沒什麼！': ['ご主人さまの手……もう一回つなぎたいな。あっ、な、なんでもないです！', 'Your hand... I want to hold it again. Oh, n-never mind!'],
    '主人，莓果以後也可以一直在這裡嗎？……嘿嘿，說好了喔！': ['ご主人さま、ベリー、これからもずっとここにいていいですか？……えへへ、約束ですよ！', 'Master, can Berry stay here always? ...Hehe, it\'s a promise!'],
    '……只是，怕你迷路。': ['……ただ、迷子になられたら困るので。', '...It\'s only so you don\'t get lost.'],
    '……手。……借你一下。': ['……手。……少しだけ、貸します。', '...Hand. ...I\'ll lend it. Briefly.'],
    '……慢一點。我跟得上。': ['……ゆっくりで。ついていけます。', '...Slower. I can keep up.'],
    '……走吧。去哪都行。': ['……行きましょう。どこへでも。', '...Let\'s go. Anywhere is fine.'],
    '……別放開。……這是命令。': ['……離さないで。……命令です。', '...Don\'t let go. ...That\'s an order.'],
    '……主人的手，我記住了。': ['……ご主人さまの手、覚えました。', '...I\'ve memorized your hand, Master.'],
    '……別拍。……拍了就算了。': ['……撮らないで。……撮ったなら、もういいです。', '...Don\'t take it. ...Well, it\'s taken now.'],
    '……這表情，不准給別人看。': ['……この顔、他の人に見せないで。', '...Don\'t show anyone this face.'],
    '……一張就好。……好好收著。': ['……一枚だけ。……大事にしてください。', '...Just one. ...Keep it safe.'],
    '……笑了嗎？……你看錯了。': ['……笑ってた？……見間違いです。', '...Was I smiling? ...You saw wrong.'],
    '……！……突然這樣，犯規。': ['……！……いきなりは、反則です。', '...! ...Out of nowhere. That\'s cheating.'],
    '……一下下。……就一下下。': ['……少しだけ。……少しだけ、ですよ。', '...Just a moment. ...Only a moment.'],
    '……心跳，太吵了。……不是我的。': ['……心臓の音、うるさい。……わたしのじゃないです。', '...Your heartbeat\'s loud. ...It\'s not mine.'],
    '……過來。……耳朵。': ['……こっちへ。……耳を。', '...Come here. ...Your ear.'],
    '……夜子這個名字，只想被主人叫。': ['……夜子って名前、ご主人さまにだけ呼ばれたいです。', '...The name Yoru. I only want you to call me by it.'],
    '……我不擅長說話。……但，喜歡主人。': ['……話すのは苦手です。……でも、ご主人さまが好きです。', '...I\'m bad with words. ...But I like you, Master.'],
    '……那個蝴蝶結，還留著。……一直。': ['……あのリボン、まだ持ってます。……ずっと。', '...That ribbon. I still have it. ...Always.'],
    '……還早。': ['……まだ早いです。', '...Too soon.'],
    '……主人。……等你。': ['……ご主人さま。……待ってました。', '...Master. ...I was waiting.'],
    '……來了。……（微笑）': ['……来ましたね。……（微笑）', '...You came. ...(smiles)'],
    '……主人。……（站在旁邊）': ['……ご主人さま。……（そばに立つ）', '...Master. ...(stands beside you)'],
    '……頭。……可以摸。': ['……頭。……なでてもいいです。', '...My head. ...You may pat it.'],
    '……嗯。……很好。': ['……ん。……よろしい。', '...Mm. ...Good.'],
    '……沒睡。……真的。': ['……寝てません。……本当です。', '...I wasn\'t asleep. ...Really.'],
    '……主人。喜歡夜晚，還是白天。': ['……ご主人さま。夜と昼、どちらが好きですか。', '...Master. Night or day. Which do you like.'],
    '夜晚': ['夜', 'Night'],
    '……嗯。夜晚安靜。……和我一樣。': ['……ん。夜は静か。……わたしと同じ。', '...Mm. Night is quiet. ...Like me.'],
    '白天': ['昼', 'Day'],
    '……是嗎。……那我就在白天，也陪著你。': ['……そうですか。……なら昼も、そばにいます。', '...I see. ...Then I\'ll stay by you in the daytime too.'],
    '……抹茶，要不要加糖。': ['……抹茶、砂糖は入れますか。', '...Matcha. Sugar or not.'],
    '不加': ['入れない', 'No sugar'],
    '……懂的人。……很好。': ['……わかってますね。……よろしい。', '...You know your tea. ...Good.'],
    '加很多': ['たっぷり', 'Lots'],
    '……（沉默）……下次，泡甜的給你。': ['……（沈黙）……次は、甘いのを淹れます。', '...(silence) ...Next time, I\'ll make yours sweet.'],
    '……如果我不見了，主人會找嗎。': ['……もしわたしがいなくなったら、探しますか。', '...If I disappeared, would you look for me.'],
    '一定會找': ['絶対に探す', 'I\'d find you'],
    '……笨蛋。……我不會走的。': ['……ばか。……どこにも行きません。', '...Idiot. ...I\'m not going anywhere.'],
    '你會回來的': ['帰ってくると信じてる', 'You\'d come back'],
    '……嗯。……不管多遠，都會回來。': ['……ん。……どんなに遠くても、帰ってきます。', '...Mm. ...However far, I\'d come back.'],
    '……我的刀，叫「月影」。……別碰。': ['……わたしの刀は「月影」。……触らないで。', '...My blade is called Tsukikage. ...Don\'t touch it.'],
    '……主人，話很多。……不討厭。': ['……ご主人さまは、よくしゃべる。……嫌いじゃないです。', '...You talk a lot, Master. ...I don\'t mind.'],
    '……任務的時候，背後交給我。': ['……任務の時、背中はわたしに任せて。', '...On a job, leave your back to me.'],
    '……今晚的月亮，很漂亮。……一起看。': ['……今夜の月、きれいです。……一緒に見ましょう。', '...The moon\'s beautiful tonight. ...Watch it with me.'],
    '……主人。……一直在。……我也是。': ['……ご主人さま。……ずっと、いてください。……わたしも。', '...Master. ...Stay, always. ...So will I.'],
    '欸？要牽手嗎？……那、那蜜糖就不會迷路了！': ['えっ？手をつなぐんですか？……じゃ、じゃあハニー、迷子にならないですね！', 'Huh? Hold hands? ...Th-then Honey won\'t get lost!'],
    '手、手心好像出汗了……欸嘿嘿。': ['手、手のひらに汗が……えへへ。', 'M-my palm\'s all sweaty... ehehe.'],
    '跟主人一起走，就不會迷路了～': ['ご主人さまと一緒なら、迷子になりません～', 'With you, I won\'t get lost~'],
    '欸嘿嘿，散步散步～要去哪裡呢？': ['えへへ、お散歩お散歩～どこへ行きましょう？', 'Ehehe, walkies walkies~ Where are we going?'],
    '主人的手暖暖的……蜜糖想一直牽著～': ['ご主人さまの手、ぽかぽか……ずっとつないでいたいです～', 'Your hand\'s so warm... Honey wants to hold it forever~'],
    '就算迷路也沒關係，因為主人在嘛～': ['迷子になっても大丈夫、ご主人さまがいますから～', 'Even if I get lost it\'s fine, \'cause you\'re here~'],
    '要、要笑嗎？像這樣？欸嘿嘿……': ['わ、笑うんですか？こうですか？えへへ……', 'Sh-should I smile? Like this? Ehehe...'],
    '欸嘿嘿，拍到蜜糖最可愛的樣子了嗎？': ['えへへ、ハニーの一番かわいいところ、撮れました？', 'Ehehe, did you get Honey\'s cutest side?'],
    '欸嘿嘿，要跟主人一起拍嗎？': ['えへへ、ご主人さまも一緒に撮りませんか？', 'Ehehe, want to be in it with me?'],
    '這張照片，蜜糖要貼在床頭～': ['この写真、ハニーのベッドの横に貼ります～', 'Honey\'s putting this photo by her bed~'],
    '哇～主人抱抱～蜜糖要融化了～': ['わぁ～ご主人さまのぎゅー～ハニー、とけちゃいます～', 'Waah~ A hug from you~ Honey\'s melting~'],
    '欸嘿嘿……好安心……好想睡……': ['えへへ……安心します……眠くなっちゃう……', 'Ehehe... so safe... so sleepy...'],
    '軟綿綿的……啊，是蜜糖自己啦。': ['ふわふわ……あっ、ハニーのことでした。', 'So squishy... oh, that\'s Honey herself.'],
    '主人主人，悄悄話喔……（小聲）': ['ご主人さま、ないしょ話です……（小声）', 'Master, Master, a secret... (whispering)'],
    '蜜糖常常迷路……可是回主人身邊的路，從來沒忘過喔。': ['ハニー、よく迷子になるけど……ご主人さまのところへ帰る道は、一度も忘れたことないんです。', 'Honey gets lost a lot... but I\'ve never once forgotten the way back to you.'],
    '兔兔跟蜜糖說，牠也最喜歡主人了～': ['うさちゃんも、ご主人さまが大好きだって言ってました～', 'Bunny told Honey it loves you best too~'],
    '蜜糖做的蛋糕……第一塊永遠是主人的。': ['ハニーが焼いたケーキ……最初の一切れは、いつもご主人さまのです。', 'The first slice of every cake Honey bakes... is always yours.'],
    '欸？那個……蜜糖還會害羞啦……': ['えっ？それは……ハニー、まだ恥ずかしいです……', 'Huh? That\'s... Honey\'s still too shy...'],
    '主人～！蜜糖好想你喔～': ['ご主人さま～！ハニー、会いたかったです～', 'Master~! Honey missed you~'],
    '欸嘿嘿，主人來了～蜜糖今天有好好記得等你喔～': ['えへへ、ご主人さまだ～ハニー、今日はちゃんと覚えて待ってました～', 'Ehehe, you\'re here~ Honey remembered to wait for you today~'],
    '主人～蜜糖找到你了～': ['ご主人さま～ハニー、見つけました～', 'Master~ Honey found you~'],
    '主人，蜜糖想被摸摸頭～': ['ご主人さま、ハニー、なでなでしてほしいです～', 'Master, Honey wants head pats~'],
    '欸嘿嘿～被發現了～': ['えへへ～バレちゃいました～', 'Ehehe~ You caught on~'],
    '主人，蜜糖剛剛要說什麼來著……主人知道嗎？': ['ご主人さま、ハニーさっき何を言おうとしてたんでしたっけ……わかります？', 'Master, what was Honey about to say just now... do you know?'],
    '想說喜歡我？': ['好きって言いたかった？', 'That you like me?'],
    '欸、欸欸！？……好、好像是那個沒錯……欸嘿嘿……': ['え、ええっ！？……そ、そうだった気がします……えへへ……', 'Wh-whaaat!? ...I-I think that was it... ehehe...'],
    '我也不知道': ['わからないな', 'No idea'],
    '對吧～那就一起想吧～……啊，想不起來了～': ['ですよね～じゃあ一緒に考えましょう～……あ、思い出せません～', 'Right~ Let\'s think together then~ ...Nope, can\'t remember~'],
    '蜂蜜蛋糕跟冰淇淋，要先吃哪個？': ['ハニーケーキとアイス、どっちから食べます？', 'Honey cake or ice cream, which do we eat first?'],
    '先吃蜂蜜蛋糕': ['ハニーケーキから', 'Honey cake first'],
    '欸嘿嘿，跟蜜糖想的一樣～！': ['えへへ、ハニーと同じ考えです～！', 'Ehehe, just what Honey was thinking~!'],
    '先吃冰淇淋': ['アイスから', 'Ice cream first'],
    '對喔，冰淇淋會融化！主人好聰明～': ['そっか、アイスはとけちゃいますもんね！ご主人さま、かしこい～', 'Oh right, ice cream melts! You\'re so smart~'],
    '主人，兔兔的名字要叫什麼好呢？': ['ご主人さま、うさちゃんの名前、何がいいと思います？', 'Master, what should we name the bunny?'],
    '叫「棉花糖」': ['「マシュマロ」', '"Marshmallow"'],
    '棉花糖！軟綿綿的，好可愛～就決定是你了！': ['マシュマロ！ふわふわでかわいい～決まりです！', 'Marshmallow! Fluffy and cute~ That\'s the one!'],
    '叫「蜜糖二號」': ['「ハニー二号」', '"Honey No. 2"'],
    '蜜糖二號……？那蜜糖是一號嗎？欸嘿嘿～': ['ハニー二号……？じゃあハニーは一号ですか？えへへ～', 'Honey No. 2...? So Honey\'s No. 1? Ehehe~'],
    '蜜糖的兔兔很會跳喔～比蜜糖還會跳～': ['ハニーのうさちゃん、ジャンプが上手なんです～ハニーより上手～', 'Honey\'s bunny is great at jumping~ Better than Honey~'],
    '主人，蜜糖今天有乖乖沒迷路喔！……大概。': ['ご主人さま、ハニー今日はちゃんと迷子にならなかったです！……たぶん。', 'Master, Honey didn\'t get lost today! ...Probably.'],
    '主人說話的聲音，蜜糖聽了就會安心～': ['ご主人さまの声を聞くと、ハニー安心します～', 'Hearing your voice makes Honey feel safe~'],
    '主人……蜜糖可以靠著你一下下嗎？好睏……': ['ご主人さま……ちょっとだけ寄りかかってもいいですか？眠くて……', 'Master... can Honey lean on you a little? So sleepy...'],
    '蜜糖最喜歡的東西……第一名是主人，第二名是蛋糕！': ['ハニーの好きなもの……一番はご主人さま、二番はケーキです！', 'Honey\'s favorite things... number one is you, number two is cake!'],
    '呵呵，要姊姊牽著你走嗎？': ['ふふ、お姉さんが手を引いてあげましょうか？', 'Hehe, shall your big sister lead you by the hand?'],
    '……主人的手，比想像中還大呢。': ['……ご主人さまの手、思ったより大きいんですね。', '...Your hand is bigger than I thought.'],
    '慢慢走就好，姊姊不會走丟的。': ['ゆっくり歩きましょう。お姉さんははぐれませんから。', 'Let\'s walk slowly. Your big sister won\'t wander off.'],
    '呵呵，這樣好像在約會呢。': ['ふふ、なんだかデートみたいですね。', 'Hehe, it\'s almost like a date.'],
    '……被主人牽著走，姊姊也會心跳加速的。': ['……ご主人さまに手を引かれると、お姉さんだってドキドキしちゃいます。', '...Even your big sister\'s heart races when you lead her by the hand.'],
    '就這樣，走到哪裡都好。': ['このまま、どこまででも。', 'Like this, anywhere at all.'],
    '呵呵，要拍得漂亮一點喔？': ['ふふ、きれいに撮ってくださいね？', 'Hehe, make it a pretty one, okay?'],
    '姊姊上相嗎？……說實話喔。': ['お姉さん、写真映りいいですか？……正直にですよ。', 'Do I photograph well? ...Be honest.'],
    '這張照片，要好好珍惜喔。': ['この写真、大事にしてくださいね。', 'Take good care of this photo, okay?'],
    '呵呵……下次，一起入鏡吧。': ['ふふ……次は、一緒に写りましょう。', 'Hehe... next time, let\'s be in it together.'],
    '呵呵，來，姊姊抱抱。……今天也辛苦了。': ['ふふ、はい、ぎゅー。……今日もお疲れさまでした。', 'Hehe, come here, a hug from your big sister. ...You worked hard today.'],
    '……被抱住的是姊姊呢。……真狡猾。': ['……抱きしめられたのは、お姉さんの方ですね。……ずるいです。', '...I\'m the one being held, it seems. ...That\'s sly of you.'],
    '就這樣待一會兒吧，不用急。': ['しばらくこのままでいましょう。急がなくていいですから。', 'Let\'s stay like this a while. There\'s no hurry.'],
    '主人，姊姊有件事只想跟你說……（小聲）': ['ご主人さま、あなたにだけ言いたいことがあるんです……（小声）', 'Master, there\'s something I want to tell only you... (whispering)'],
    '……其實，姊姊也想被寵一下。': ['……本当は、お姉さんだって甘えたいんです。', '...Honestly, your big sister wants to be spoiled too.'],
    '每天等主人回來，是姊姊最喜歡的時間。': ['毎日ご主人さまの帰りを待つ時間が、お姉さんの一番好きな時間です。', 'Waiting for you to come home each day is my favorite time.'],
    '……以後不用叫姊姊了。叫「雪乃」就好。': ['……これからは「お姉さん」じゃなくて、「雪乃」って呼んでください。', '...From now on, don\'t call me big sister. Just \'Yukino\'.'],
    '呵呵，那個嘛……等我們更親近一點再說吧。': ['ふふ、それは……もう少し仲良くなってからにしましょう。', 'Hehe, that... let\'s save it until we\'re a little closer.'],
    '主人，歡迎回來。姊姊好想你。': ['おかえりなさい、ご主人さま。お姉さん、会いたかったです。', 'Welcome back, Master. Your big sister missed you.'],
    '呵呵，終於來了。今天要讓姊姊好好寵你喔。': ['ふふ、やっと来ましたね。今日はお姉さんにたっぷり甘やかされてください。', 'Hehe, finally. Today, let your big sister spoil you properly.'],
    '主人，要不要休息一下？姊姊陪你。': ['ご主人さま、少し休みませんか？お姉さんが付き合いますよ。', 'Master, shall we take a break? I\'ll keep you company.'],
    '呵呵……偶爾，也想被主人摸摸頭呢。': ['ふふ……たまには、ご主人さまになでられたいです。', 'Hehe... once in a while, I\'d like a head pat from you too.'],
    '……呵呵，謝謝主人。': ['……ふふ、ありがとうございます、ご主人さま。', '...Hehe, thank you, Master.'],
    '主人，累的時候都怎麼放鬆呢？': ['ご主人さま、疲れた時はどうやって休んでいますか？', 'Master, how do you unwind when you\'re tired?'],
    '跟你聊天': ['こうして話すこと', 'Talking with you'],
    '……呵呵，這麼說的話，姊姊可要天天陪你了。': ['……ふふ、そう言われたら、毎日付き合っちゃいますよ。', '...Hehe, if you say that, I\'ll have to keep you company every day.'],
    '睡覺': ['寝ること', 'Sleeping'],
    '那姊姊幫你把枕頭拍得軟軟的吧。': ['じゃあ、お姉さんが枕をふかふかにしておきますね。', 'Then I\'ll fluff up your pillow for you.'],
    '主人喜歡什麼樣的故事呢？': ['ご主人さまは、どんなお話が好きですか？', 'What kind of stories do you like, Master?'],
    '冒險故事': ['冒険もの', 'Adventures'],
    '呵呵，很像主人呢。下次姊姊念給你聽。': ['ふふ、ご主人さまらしいですね。今度読んであげます。', 'Hehe, that suits you. I\'ll read you one sometime.'],
    '戀愛故事': ['恋愛もの', 'Romance'],
    '……呵呵，主人也會在意這種事呀？': ['……ふふ、ご主人さまもそういうの、気になるんですね？', '...Hehe, so you care about that kind of thing too?'],
    '如果姊姊累了，主人會怎麼做呢？': ['もしお姉さんが疲れていたら、ご主人さまはどうしますか？', 'If your big sister were tired, what would you do?'],
    '換我照顧你': ['今度はこっちが面倒を見る', 'I\'d take care of you'],
    '……呵呵，真可靠。那就麻煩你囉。': ['……ふふ、頼もしいですね。じゃあ、お願いしちゃいます。', '...Hehe, how dependable. Then I\'ll leave it to you.'],
    '給你冰淇淋': ['アイスをあげる', 'I\'d bring you ice cream'],
    '呵呵，被看穿了呢。姊姊最喜歡了。': ['ふふ、お見通しですね。お姉さんの大好物です。', 'Hehe, you see right through me. It\'s my favorite.'],
    '有什麼不懂的，都可以問姊姊喔。': ['わからないことがあったら、何でもお姉さんに聞いてくださいね。', 'If there\'s anything you don\'t know, just ask your big sister.'],
    '呵呵，主人今天也很努力呢。姊姊都看在眼裡。': ['ふふ、今日もがんばってますね。お姉さんはちゃんと見てますよ。', 'Hehe, you\'re working hard today too. I see it all.'],
    '主人的笑容，是姊姊最好的獎勵。': ['ご主人さまの笑顔が、お姉さんへの一番のごほうびです。', 'Your smile is the best reward your big sister could ask for.'],
    '……主人，姊姊偶爾也想撒嬌一下，可以嗎？': ['……ご主人さま、お姉さんもたまには甘えていいですか？', '...Master, may your big sister be spoiled once in a while?'],
    '以後的每一天，都想和主人一起度過。': ['これからの毎日を、ご主人さまと一緒に過ごしたいです。', 'Every day from now on, I want to spend with you.'],
    // ---- boss parts and curses
    '鑽頭': ['ドリル', 'Drill'],
    '金色感應耳': ['金のセンサー耳', 'Gold sensor ears'],
    '火焰頭': ['炎の頭', 'Flame head'],
    '左側的腳': ['左の脚', 'Left legs'],
    '右側的腳': ['右の脚', 'Right legs'],
    '玻璃罩': ['ガラスドーム', 'Glass dome'],
    '左鉗臂': ['左アーム', 'Left claw'],
    '右鉗臂': ['右アーム', 'Right claw'],
    '腳步變慢': ['足が重い', 'Slow feet'],
    '火力變小': ['火力ダウン', 'Weak fire'],
    '放不了炸彈': ['ボムが置けない', 'No bombs'],
    '方向顛倒': ['あべこべ', 'Reversed'],
    '停不下來的炸彈': ['ボムが止まらない', 'Bomb frenzy'],
    // ---- capsule toys
    '零錢包': ['小銭入れ', 'Coin purse'],
    '小禮物': ['プレゼント', 'Little gift'],
    '甜點招待券': ['スイーツ招待券', 'Sweets voucher'],
    '金幣袋': ['コイン袋', 'Coin bag'],
    '卡片': ['カード', 'Card'],
    '家具': ['家具', 'Furniture'],
    '大獎': ['大当たり', 'Jackpot'],
    // ---- the maids' expression cards
    '暴怒': ['激おこ', 'Furious'],
    '得意': ['ドヤ顔', 'Smug'],
    '元氣': ['元気', 'Peppy'],
    '哭哭': ['えーん', 'Sniffles'],
    '超開心': ['大よろこび', 'Overjoyed'],
    '比YA': ['ピース', 'Peace sign'],
    '驚嘆': ['わあっ', 'Amazed'],
    '溫柔': ['やさしい笑顔', 'Gentle'],
    '偷笑': ['くすくす', 'Giggle'],
    '慌張': ['あわあわ', 'Panic'],
    '自豪': ['えっへん', 'Proud'],
    '興奮': ['ワクワク', 'Excited'],
    '平靜': ['おだやか', 'Calm'],
    '尷尬': ['気まずい', 'Awkward'],
    '滿足': ['満足', 'Content'],
    '不悅': ['ふきげん', 'Displeased'],
    '生氣': ['おこ', 'Angry'],
    '嫌棄': ['ジト目', 'Disdain'],
    '哭泣': ['なみだ', 'Tears'],
    '驚嚇': ['びっくり', 'Startled'],
    '害羞': ['てれてれ', 'Shy'],
    '倒茶': ['お茶をどうぞ', 'Tea time'],
    '驚喜': ['うれしい驚き', 'Delighted'],
    '擔心': ['心配', 'Worried'],
    '鬧彆扭': ['すねてる', 'Sulking'],
    '暈頭轉向': ['ぐるぐる', 'Dizzy'],
    '發呆': ['ぽーっ', 'Daydream'],
    '緊張': ['ドキドキ', 'Nervous'],
    '收到禮物': ['プレゼント', 'A present!'],
    '手忙腳亂': ['てんやわんや', 'Flustered'],
    '好奇': ['興味しんしん', 'Curious'],
    '自信': ['自信たっぷり', 'Confident'],
    '誘惑': ['ゆうわく', 'Alluring'],
    '傲慢': ['高飛車', 'Haughty'],
    '嚴肅': ['真剣', 'Serious'],
    '悲傷': ['かなしい', 'Sad'],
    '期待': ['期待', 'Eager'],
    '疲憊': ['おつかれ', 'Tired'],
    '調皮': ['いたずら', 'Teasing'],
    '驚訝': ['おどろき', 'Surprised'],
    // ---- what each maid says at each piece of furniture
    '水！給我長高高——！嘿咻！': ['お水っ！ぐんぐん育てーっ！えいっ！', 'Water! Grow big and strong — hup!'],
    '兔兔！陪我練習抱摔——開玩笑的啦！': ['うさちゃん！投げ技の練習――なんてね！', 'Bun-bun! Practise throws with me — kidding!'],
    '開飯囉！一、二、三，搶食比賽開始！': ['ごはんだ！いち、に、さん、競争スタート！', 'Dinner! One, two, three — race for it!'],
    '頭髮又翹起來了！壓一壓……好，出發！': ['また寝ぐせ！ぺたん……よし、いくぞ！', 'My hair\'s sticking up again! Pat it down... right, let\'s go!'],
    '呼——！剛剛的特訓超累的！再五分鐘就好！': ['ふぅーっ！さっきの特訓きつかった！あと五分だけ！', 'Phew! That training was brutal — five more minutes!'],
    '這首超燃！跟著節奏動起來——！': ['この曲アツい！リズムに乗って動くぞーっ！', 'This one\'s a banger! Move to the beat!'],
    '開燈！這樣才看得清楚敵人……啊，沒有敵人。': ['点けた！これで敵が見え……あ、敵いないや。', 'Lights on! Now I can see the enem— oh. No enemies.'],
    '我只會彈這首——嘿！咚咚咚！': ['弾けるのはこれだけ――えいっ！ドンドンドン！', 'This is the only tune I know — hah! Bang bang bang!'],
    '地毯！翻滾練習的最佳場地！': ['ラグ！受け身の練習にぴったり！', 'A rug! Perfect for practising rolls!'],
    '睡飽才有力氣！晚安，主人！': ['寝たら元気！おやすみ、ご主人さま！', 'Sleep means strength! Good night, Master!'],
    '特訓時間！今天要打破紀錄！': ['特訓の時間！今日は記録を破るぞ！', 'Training time! Today I break my record!'],
    '換班？好啊——大家一起上！': ['交代？いいよ――みんなでいこう！', 'Swapping? Sure — all of us together!'],
    '茶！還有點心！點心呢——？': ['お茶！おやつは！おやつはー？', 'Tea! And snacks! Where are the snacks?'],
    '這本是我的成長紀錄！看看我變多強！': ['これ、あたしの成長記録！どれだけ強くなったか見て！', 'That\'s my growth log! See how much stronger I am!'],
    '今天份的已經做完啦！明天再一起！': ['今日のぶんはもう終わり！明日また一緒に！', 'Today\'s is done! Let\'s do it again tomorrow!'],
    '咦？剛剛是不是已經澆過了……？再一點點好了。': ['あれ？さっきもあげたような……もうちょっとだけ。', 'Huh? Didn\'t I just water it...? A little more, then.'],
    '呼……兔兔最會聽人說話了呢。': ['ふぁ……うさちゃんはお話を聞くのが上手ですねぇ。', 'Aah... Bun-bun is such a good listener.'],
    '啊，飼料……咦，我剛剛是不是倒太多了？': ['あ、えさ……あれ、入れすぎちゃいました？', 'Oh, the food... wait, did I put in too much?'],
    '咦，髮夾……剛剛明明放在這裡的……': ['あれ、ヘアピン……ここに置いたはずなのに……', 'Huh, my hairpin... I\'m sure I left it right here...'],
    '這裡好軟……主人，我睡一下下就好……呼……': ['ふかふか……ご主人さま、ちょっとだけ……すぅ……', 'So soft... Master, just a little nap... zzz...'],
    '啊，這首歌……咦，歌名是什麼來著？': ['あ、この曲……えっと、なんて曲でしたっけ？', 'Oh, this song... um, what was it called again?'],
    '暖暖的……啊，飛蛾！沒事沒事，不要怕～': ['あったかい……あ、蛾！だいじょうぶ、こわくないよ～', 'So warm... oh, a moth! It\'s all right, don\'t be scared.'],
    '咦……啊，彈錯了。再、再一次！': ['あれ……あっ、まちがえた。も、もう一回！', 'Huh... ah, wrong note. O-one more time!'],
    '毛毛的……在這裡打滾一下下好了……': ['もふもふ……ちょっとだけごろごろしちゃおうかな……', 'So fluffy... maybe just a little roll around...'],
    '棉被……啊，是不是忘了關燈……算了……': ['おふとん……あ、電気消したかな……まあいっか……', 'The covers... oh, did I turn off the light... never mind...'],
    '筆記……咦，昨天寫到哪裡了呢？': ['ノート……あれ、昨日どこまで書きましたっけ？', 'My notes... erm, where did I leave off yesterday?'],
    '咦，我的圍裙……啊，穿在身上。': ['あれ、わたしのエプロン……あ、着てました。', 'Huh, my apron... oh. I\'m wearing it.'],
    '我來倒……啊，滿出來了！等、等一下！': ['わたしが注ぎ……あっ、あふれちゃう！ま、まって！', 'I\'ll pour — ah, it\'s overflowing! W-wait!'],
    '咦，書怎麼倒了……啊，是我放反了。': ['あれ、本が倒れて……あっ、逆さに入れてました。', 'Oh, the books fell... ah, I shelved one upside down.'],
    '咦……好像已經做過了？嗯，做過了。': ['あれ……もうやった気が？うん、やりました。', 'Hmm... did I already? Yes. I did.'],
    '葉子上的灰塵也擦一擦……好，這樣才漂亮。': ['葉っぱのほこりも拭いて……はい、これできれいですね。', 'Let me dust the leaves too... there, much better.'],
    '呵呵，主人也想抱抱嗎？姊姊讓給你喔。': ['ふふ、ご主人さまも抱きたいですか？お姉さんが譲りますよ。', 'Hehe, would you like a turn? Your big sister will share.'],
    '水溫也要顧好喔。金魚是很怕冷的。': ['水温も見てあげないと。金魚は寒がりですから。', 'Mind the water\'s warmth; goldfish feel the cold.'],
    '主人，姊姊今天的髮型……還可以嗎？': ['ご主人さま、お姉さんの今日の髪型……変じゃないですか？', 'Master, my hair today... does it look all right?'],
    '主人也坐下吧？姊姊的腿可以借你。': ['ご主人さまも座ります？お姉さんの膝、貸しますよ。', 'Sit with me? You may borrow my lap.'],
    '這張唱片很有味道呢。要一起聽嗎？': ['このレコード、味がありますね。一緒に聴きます？', 'This record has character. Shall we listen together?'],
    '燈光調暗一點，眼睛比較舒服喔。': ['灯りは少し落としたほうが、目に優しいですよ。', 'A softer light is kinder on the eyes.'],
    '小時候學過一點點。……還記得呢。': ['子どものころ少しだけ。……まだ覚えてました。', 'I learned a little as a child. ...I still remember.'],
    '地毯下面也要掃喔，灰塵最愛躲在那裡。': ['ラグの下も掃かないと。ほこりの隠れ家ですから。', 'Sweep under it too — dust loves hiding there.'],
    '主人也早點休息喔。姊姊會擔心的。': ['ご主人さまも早めに休んでくださいね。心配しますから。', 'Do rest early too. Your big sister worries.'],
    '先複習昨天的，再往前走一步。': ['昨日の復習から。それから一歩先へ。', 'Review yesterday first, then one step further.'],
    '要換誰來值班呢？姊姊都可以喔。': ['誰に代わりましょうか？お姉さんはどちらでも。', 'Who shall take over? Either way suits me.'],
    '今天泡的是紅茶。慢慢喝，不用急。': ['今日は紅茶です。ゆっくりどうぞ、急がなくていいですよ。', 'Black tea today. Take your time; there\'s no rush.'],
    '書要照順序放，找起來才快喔。': ['本は順番に並べると、探すのが早いですよ。', 'Shelve them in order and they\'re quicker to find.'],
    '今天已經好囉。明天再說吧？': ['今日はもう済んでますよ。続きは明日にしましょう？', 'That\'s done for today. Shall we continue tomorrow?'],
    '……喝吧。長不大的話，我可不管你。': ['……飲んで。育たなかったら知らないから。', '...Drink. Don\'t blame me if you stay small.'],
    '……只有現在。看到了就當作沒看到。': ['……今だけ。見たことは忘れて。', '...Just for a moment. Forget you saw this.'],
    '……吃吧。被養著的感覺，不壞吧。': ['……食べて。飼われるのも悪くないでしょ。', '...Eat. Being kept isn\'t so bad, is it.'],
    '……看什麼。轉過去。': ['……なに見てるの。あっち向いて。', '...What are you looking at. Turn around.'],
    '……這個位子是我的。要坐的話，坐地上。': ['……ここは私の席。座るなら床で。', '...This seat is mine. You can have the floor.'],
    '……安靜一點的曲子。吵的話，我就關掉。': ['……静かな曲を。うるさかったら止める。', '...Something quiet. Too loud and I stop it.'],
    '……太亮了。這樣剛好。': ['……眩しい。これくらいでいい。', '...Too bright. This is enough.'],
    '……（一個低音）。這樣就夠了。': ['……（低い音をひとつ）。これで十分。', '...(one low note). That will do.'],
    '……踩起來，還不錯。': ['……踏み心地は、悪くない。', '...Feels fine underfoot.'],
    '……先說好，不准偷看我的睡臉。': ['……先に言っておく。寝顔を覗いたら許さない。', '...One thing: peek at my sleeping face and you\'re finished.'],
    '……看著。學得起來就算你厲害。': ['……見てて。覚えられたら大したもの。', '...Watch. Learn it and I\'ll be impressed.'],
    '……我的衣服，別亂碰。': ['……私の服には触らないで。', '...Don\'t touch my clothes.'],
    '……茶泡好了。涼掉的話，是你的錯。': ['……お茶、淹れた。冷めたらあなたのせい。', '...Tea\'s ready. If it goes cold, that\'s on you.'],
    '……這本，寫著你的事。要看嗎。': ['……これ、あなたのことが書いてある。読む？', '...This one\'s about you. Want to read it?'],
    '……今天已經夠了。別貪心。': ['……今日はもう十分。欲張らないで。', '...That\'s enough for today. Don\'t get greedy.'],
    // ---- each maid's own room: her furniture, her paper and floor, and what she says there
    '沙包': ['サンドバッグ', 'Punching bag'],
    '莓果專用。打一輪，心情 +5、力量經驗 +4。': ['ベリー専用。一本打てば気分+5、パワー経験+4。', 'Berry\'s own. A round on it: +5 mood, +4 power XP.'],
    '玩具箱': ['おもちゃ箱', 'Toy chest'],
    '蜜糖專用。翻玩具，心情 +6。': ['ハニー専用。おもちゃをあさって気分+6。', 'Honey\'s own. Rummage through it: +6 mood.'],
    '玫瑰花瓶': ['バラの花びん', 'Rose vase'],
    '雪乃專用。插花整理，心情 +5、好感 +1。': ['雪乃専用。花を活けて気分+5、好感+1。', 'Yukino\'s own. Arrange them: +5 mood, +1 affection.'],
    '和式屏風': ['和風びょうぶ', 'Folding screen'],
    '夜子專用。她會躲到屏風後面。': ['夜子専用。その後ろに隠れます。', 'Yoru\'s own. She slips behind it.'],
    '蕾絲壁紙': ['レースの壁紙', 'Lace paper'],
    '和式紙門': ['障子の壁', 'Shoji wall'],
    '榻榻米': ['畳', 'Tatami'],
    '看我的——！一、二、三！打完精神百倍！': ['見てて――！いち、に、さん！スッキリした！', 'Watch this — one, two, three! Feeling sharp now!'],
    '哇……好多玩具！咦，這個是什麼來著？': ['わぁ……おもちゃがいっぱい！あれ、これ何でしたっけ？', 'Wow... so many toys! Huh, what was this one again?'],
    '花也要修剪過才漂亮喔。主人想要哪一朵？': ['お花も切りそろえると綺麗ですよ。どれがいいですか？', 'Flowers look better trimmed. Which one would you like?'],
    '……我在這後面。找得到再說。': ['……この後ろにいる。見つけられたらね。', '...I\'m behind this. Find me if you can.'],
    // ---- the café's counters: who keeps each one and what they say
    '企鵝老闆': ['ペンギン店長', 'Penguin Chef'],
    '雪寶寶店員': ['ゆきんこ店員', 'Snowkid Clerk'],
    '熊木匠': ['クマの大工', 'Bear Carpenter'],
    '寶石技師': ['ジュエル技師', 'Jewel Engineer'],
    '塵塵貓': ['ホコリねこ', 'Dust Cat'],
    '糖果龍': ['キャンディドラゴン', 'Candy Dragon'],
    '歡迎光臨～': ['いらっしゃい～', 'Welcome!'],
    '謝謝惠顧！': ['まいどどうも！', 'Thank you!'],
    '金幣不夠喔': ['コインが足りない', 'Not enough'],
    '挑個禮物吧': ['プレゼントどう？', 'Pick a gift'],
    '她會開心的': ['きっと喜ぶよ', 'She\'ll love it'],
    '差一點呢…': ['あと少し…', 'So close...'],
    '都是我做的': ['全部手作りだ', 'All handmade'],
    '幫你搬過去': ['運んでおくよ', 'I\'ll deliver it'],
    '錢還不夠喔': ['まだ足りないぞ', 'Still short'],
    '要強化嗎？': ['強化するか？', 'An upgrade?'],
    '調整完成。': ['調整、完了。', 'Tuned up.'],
    '預算不足。': ['予算不足だ。', 'Funds short.'],
    '轉一次嘛～': ['一回まわそ～', 'One spin~'],
    '喵！好運！': ['にゃ！幸運を！', 'Mew! Luck!'],
    '喵…不夠喔': ['にゃ…足りない', 'Mew... short'],
    '來抽卡吧！': ['カード引こう！', 'Draw a card!'],
    '下張說不定': ['次はSSRかも', 'Next is SSR?'],
    '金幣不夠…': ['コインが…', 'Not enough...'],
    '那道已經備好': ['ご注文済みです', 'Already in!'],
    '那件你有啦': ['もうお持ちです', 'You own it'],
    '已到極限了。': ['もう最大値だ。', 'Maxed out.'],
    '歡迎再光臨～': ['またおいで～', 'Come again!'],
    '再來看看吧': ['また見にきて', 'Look in again'],
    '慢走喔': ['気をつけてな', 'Mind how you go'],
    '恭候再訪。': ['またのお越しを。', 'Until next time.'],
    '喵～再來玩': ['にゃ～またね', 'Mew~ come back'],
    '下次見！': ['また今度！', 'See you!'],
    '今天現烤的': ['焼きたてだよ', 'Fresh-baked!'],
    '要配紅茶嗎': ['紅茶もどう？', 'Tea with it?'],
    '可以包緞帶': ['リボン包める', 'Wrapped free'],
    '她喜歡什麼': ['好み分かる？', 'Her taste?'],
    '木頭我挑的': ['木は俺が選ぶ', 'My own wood'],
    '要量尺寸嗎': ['寸法測る？', 'Need sizes?'],
    '要定期保養。': ['整備は定期的に', 'Service it.'],
    '數值不騙人。': ['数値は嘘つかん', 'Data rules.'],
    '今天手氣如何': ['今日の運は？', 'Lucky today?'],
    '再一次嘛喵': ['もう一回にゃ', 'One more~'],
    '稀有卡看運氣': ['レアは運次第', 'Rares? Luck.'],
    '收集起來吧': ['集めようよ', 'Collect them'],
  });
})(window);
