/* 炸彈女僕 BOMB MAIDS — data & dialogue text. key: 中文 source → [日本語, English] */
(function (G) {
  'use strict';
  G.addTr({
    // ---- maids
    '莓果': ['ベリー', 'Berry'],
    '空手道': ['空手', 'karate'],
    '草莓大福': ['いちご大福', 'Berry Mochi'],
    '飛踢炸彈': ['ボムキック', 'Bomb Kick'],
    '走向炸彈就能把它踢飛，': ['ボムに向かって歩くとけり飛ばせる。', 'Walk into a bomb to kick it. '],
    '按特技鍵也能踢出面前的炸彈。': ['特技キーで目の前のボムもキック！', 'The skill key kicks the bomb in front.'],
    '今天也要元氣滿滿地打掃！': ['今日も元気いっぱいおそうじです！', "Let's clean with all our might today!"],
    '夜子': ['夜子', 'Yoru'],
    '劍道': ['剣道', 'kendo'],
    '抹茶': ['抹茶', 'matcha'],
    '居合斬': ['居合斬り', 'Iai Slash'],
    '斬開面前一格的障礙物或怪物，': ['目の前の障害物やモンスターを斬り、', 'Cuts the block or monster in front, '],
    '還能把炸彈斬成兩半拆除。': ['ボムも真っ二つにして解体する。', 'and can slice a bomb to defuse it.'],
    '主人，請退後。灰塵由我來斬。': ['ご主人さま、お下がりを。ホコリは私が斬ります。', 'Stand back, Master. I shall cut the dust.'],
    '蜜糖': ['ハニー', 'Honey'],
    '烤點心': ['お菓子作り', 'baking'],
    '蜂蜜蛋糕': ['ハニーケーキ', 'Honey Cake'],
    '甜心魔法': ['スイート魔法', 'Sweet Magic'],
    '回復 1 顆愛心，': ['ハートを1つ回復して、', 'Restores 1 heart '],
    '並讓附近的怪物暈頭轉向。': ['近くのモンスターをメロメロにする。', 'and dazes nearby monsters.'],
    '點心烤好了～怪物們也乖乖的喔♪': ['お菓子が焼けました～モンスターさんもいい子にね♪', 'Treats are ready~ Be good, monsters♪'],
    '雪乃': ['雪乃', 'Yukino'],
    '讀書': ['読書', 'reading'],
    '冰淇淋': ['アイス', 'ice cream'],
    '遙控引爆': ['リモコン起爆', 'Remote Blast'],
    '立刻引爆自己放下的所有炸彈。': ['自分のボムを全部すぐに起爆する。', 'Instantly detonates all her bombs. '],
    '她的炸彈引信比較長。': ['彼女のボムは導火線が長め。', 'Her bombs have longer fuses.'],
    '計算完畢。爆破時機，完美。': ['計算完了。爆破のタイミング、完璧です。', 'Calculation complete. Perfect blast timing.'],

    // ---- monsters
    '塵塵貓': ['ホコリネコ', 'Dust Cat'],
    '住在課桌底下的灰塵團。': ['机の下にすむホコリのかたまり。', 'A dust bunny living under desks.'],
    '貪吃豬': ['くいしんブタ', 'Glutton Pig'],
    '把福利社的麵包吃光光。': ['購買部のパンを食べつくした。', 'Ate every roll in the school store.'],
    '暴走熊': ['ぼうそうクマ', 'Rampage Bear'],
    '會追著女僕跑的布偶熊。': ['メイドを追いかけるぬいぐるみ。', 'A stuffed bear that chases maids.'],
    '果凍怪': ['ぷるぷるゼリー', 'Jelly Blob'],
    '能穿過家具的軟Q果凍。': ['家具をすり抜けるゼリー。', 'A wobbly jelly that slips through furniture.'],
    '企鵝紳士': ['ペンギン紳士', 'Sir Penguin'],
    '一旦開跑就停不下來。': ['走り出したら止まらない。', 'Once he runs, he never stops.'],
    '雪寶寶': ['ゆきんこ', 'Snow Kid'],
    '會躲開炸彈的聰明雪人。': ['ボムをよける賢い雪だるま。', 'A clever snowman that dodges bombs.'],
    '杯子蛋糕怪': ['カップケーキ魔', 'Cupcake Fiend'],
    '奶油很厚，要炸兩次。': ['クリームが厚くて2回当てないと倒せない。', 'Thick frosting. Takes two hits.'],
    '糖果龍': ['アメドラゴン', 'Candy Dragon'],
    '檸檬冠毛的甜點守衛。': ['レモンのとさかのお菓子の番人。', 'A dessert guard with a lemon crest.'],

    // ---- jobs
    '教室大掃除': ['教室大そうじ', 'Class Cleanup'],
    '櫻丘學園 校長': ['桜丘学園の校長先生', 'Principal, Sakuraoka School'],
    '放學後的教室被塵塵貓佔領了。': ['放課後の教室がホコリネコに占領された。', 'Dust Cats took over the classroom after school.'],
    '請把牠們通通清掉！': ['全部やっつけてください！', 'Please clear them all out!'],
    '福利社的貪吃鬼': ['パンどろぼう', 'Snack Thief'],
    '學生會長': ['生徒会長', 'Student Council President'],
    '福利社的麵包被吃光了！': ['購買部のパンが食べられた！', 'Every roll in the school store is gone!'],
    '犯人好像是粉紅色的……': ['犯人はピンク色らしい…', 'The culprit seems to be pink...'],
    '玫瑰花園除蟲': ['花園パニック', 'Rose Garden'],
    '花園伯爵夫人': ['庭園の伯爵夫人', 'The Garden Countess'],
    '暴走熊在玫瑰園裡橫衝直撞。': ['ぼうそうクマがバラ園であばれている。', 'Rampage Bears are running wild in the roses.'],
    '別讓牠們弄壞樹屋！': ['ツリーハウスを壊させないで！', "Don't let them wreck the tree house!"],
    '果凍迷宮': ['ゼリーの迷宮', 'Jelly Maze'],
    '園丁老爺爺': ['庭師のおじいさん', 'The Old Gardener'],
    '果凍怪會穿過花叢！': ['ゼリーは花だんをすり抜ける！', 'Jellies slip right through the flowerbeds!'],
    '聽說牠們最怕長長的火力。': ['長い爆風が苦手らしい。', 'They say long blasts scare them.'],
    '雪原的企鵝管家': ['ペンギン執事', 'Penguin Butler'],
    '冰雪山莊': ['氷雪の山荘', 'Snowy Lodge'],
    '企鵝紳士跑得飛快。': ['ペンギン紳士はとても速い。', 'Sir Penguin runs very fast.'],
    '在牠的路上等著放炸彈吧。': ['通り道にボムを置いて待とう。', 'Wait on his path with a bomb.'],
    '聰明的雪寶寶': ['天才雪ん子', 'Clever Snowkids'],
    '雪寶寶會躲炸彈。': ['ゆきんこはボムをよける。', 'Snow Kids dodge bombs.'],
    '用連環爆炸把牠逼進死角！': ['連鎖爆発で追いつめよう！', 'Corner them with chain blasts!'],
    '糖果城堡的午茶': ['お城のお茶会', 'Castle Teatime'],
    '甜點女王': ['スイーツ女王', 'The Dessert Queen'],
    '杯子蛋糕怪的奶油很厚，': ['カップケーキ魔はクリームが厚く、', 'Cupcake Fiends have thick frosting, '],
    '要炸兩次才會投降。': ['2回当てないと降参しない。', 'so they need two hits.'],
    '甜點大暴走': ['スイーツ暴走', 'Dessert Riot'],
    '糖果龍帶著大軍來了！': ['アメドラゴンが大軍を連れてきた！', 'Candy Dragons brought an army!'],
    '這是最後的甜點防衛戰。': ['最後のお菓子防衛戦です。', 'This is the final dessert defense.'],
    '所有灰塵的源頭——': ['すべてのホコリの元凶——', 'The source of all the dust:'],
    '神秘研究所的巨大機甲！': ['なぞの研究所の巨大メカ！', ' a giant mech in a secret lab!'],

    // ---- café menu, upgrades, cards
    '草莓蛋糕': ['いちごケーキ', 'Strawberry Cake'],
    '下個委託 愛心 +1': ['次の依頼 ハート+1', 'Next job: Hearts +1'],
    '焦糖布丁': ['カラメルプリン', 'Caramel Pudding'],
    '下個委託 火力 +1': ['次の依頼 火力+1', 'Next job: Fire +1'],
    '冰拿鐵': ['アイスラテ', 'Iced Latte'],
    '下個委託 速度 +1': ['次の依頼 スピード+1', 'Next job: Speed +1'],
    '伯爵紅茶': ['アールグレイ', 'Earl Grey'],
    '下個委託 開場特技全滿': ['次の依頼 特技MAXで開始', 'Next job: start with full SP'],
    '炸彈提籃': ['ボムかご', 'Bomb Basket'],
    '炸彈數量 +1': ['ボムの数+1', 'Bombs +1'],
    '火力掃把': ['火力ほうき', 'Fire Broom'],
    '火力 +1': ['火力+1', 'Fire +1'],
    '輕盈皮鞋': ['かるい靴', 'Light Shoes'],
    '速度 +1': ['スピード+1', 'Speed +1'],
    '蕾絲圍裙': ['エプロン', 'Lace Apron'],
    '愛心上限 +1': ['ハート上限+1', 'Max hearts +1'],
    '研究所的最終兵器。': ['研究所の最終兵器。', "The lab's ultimate weapon."],
    '女僕炸彈': ['メイドボム', 'Maid Bomb'],
    '戴著蕾絲髮箍的炸彈。': ['レースのカチューシャをつけたボム。', 'A bomb wearing a lace headband.'],

    // ---- room
    '小房間': ['小さいお部屋', 'Small room'],
    '中房間': ['ふつうのお部屋', 'Medium room'],
    '大房間': ['広いお部屋', 'Large room'],
    '兔兔壁紙': ['うさぎ壁紙', 'Bunny'],
    '草莓牛奶條紋': ['いちごミルク柄', 'Berry Milk Stripes'],
    '草莓點點': ['いちごドット', 'Strawberry Dots'],
    '星空壁紙': ['星空壁紙', 'Starry Night'],
    '木地板': ['木の床', 'Wood'],
    '粉紅地毯': ['ピンクのじゅうたん', 'Pink Carpet'],
    '格子磁磚': ['チェックのタイル', 'Checker Tile'],
    '小木床': ['木のベッド', 'Wooden Bed'],
    '在這裡休息到隔天。': ['ここで明日まで休む。', 'Rest here until morning.'],
    '公主床': ['お姫さまベッド', 'Princess Bed'],
    '睡醒時心情 +15。': ['起きたとき気分+15。', 'Wake up with Mood +15.'],
    '書桌': ['つくえ', 'Desk'],
    '在這裡進行特訓。': ['ここで特訓する。', 'Train here.'],
    '下午茶桌': ['ティーテーブル', 'Tea Table'],
    '可以一起喝下午茶。': ['いっしょにお茶できる。', 'Have tea together.'],
    '書櫃': ['本だな', 'Bookshelf'],
    '特訓經驗值 +20%。': ['特訓の経験値+20%。', 'Training EXP +20%.'],
    '盆栽': ['はち植え', 'Potted Plant'],
    '澆水讓心情變好。': ['水やりで気分アップ。', 'Watering lifts the mood.'],
    '兔兔抱枕': ['うさぎクッション', 'Bunny Cushion'],
    '摸頭時好感度多 +1。': ['なでなでで好感度+1。', 'Head pats give +1 more affection.'],
    '愛心地毯': ['ハートのラグ', 'Heart Rug'],
    '心情不容易變差。': ['気分が下がりにくい。', 'Mood drops more slowly.'],
    '小鋼琴': ['小さなピアノ', 'Little Piano'],
    '每天聽女僕彈一曲。': ['毎日1曲弾いてくれる。', 'She plays you a song each day.'],
    '立燈': ['フロアランプ', 'Floor Lamp'],
    '溫暖的燈光。': ['あたたかい灯り。', 'A warm glow.'],
    '鼓鼓兔': ['ドラムうさぎ', 'Drum Bunny'],
    '敲著小鼓追過來的兔子。': ['小太鼓をたたいて追いかけてくる。', 'Chases you while banging its drum.'],
    '寶石騎士': ['ジュエルナイト', 'Gem Knight'],
    '盔甲很硬，要炸兩次。': ['よろいが硬く、2回当てないと倒れない。', 'Hard armor: it takes two blasts.'],
    '城堡地下出現了噴火的機械蜘蛛！': ['お菓子城の地下に火をふく機械グモ！', 'A fire-breathing robot spider under the castle!'],
    '玩具箱演唱會': ['おもちゃライブ', 'Toy Box Concert'],
    '玩具店老闆': ['おもちゃ屋の店長', 'Toy Shop Owner'],
    '玩具們在舞台上開起了演唱會！': ['おもちゃたちがステージでライブ中！', 'The toys are putting on a concert!'],
    '鼓鼓兔會追著人跑，小心被包圍。': ['ドラムうさぎは追ってくる。囲まれないで。', 'Drum Bunnies chase you. Don\'t get surrounded.'],
    '積木迷宮': ['つみき迷路', 'Block Maze'],
    '積木塔堆成了迷宮。': ['つみきの塔が迷路になっている。', 'Block towers form a maze.'],
    '用炸彈打通一條路吧！': ['ボムで道をひらこう！', 'Blast a path through!'],
    '寶石宮殿': ['ジュエルパレス', 'Jewel Palace'],
    '寶石公主': ['宝石のお姫さま', 'Jewel Princess'],
    '宮殿中央的巨大寶石蛋被盯上了！': ['宮殿の宝石たまごが狙われている！', 'The palace\'s giant jewel egg is in danger!'],
    '寶石騎士很硬，要炸兩次。': ['ジュエルナイトは2回当てよう。', 'Gem Knights take two hits.'],
    '閃耀迴廊': ['きらめき回廊', 'Crystal Hall'],
    '水晶柱排成菱形的迴廊。': ['水晶の柱がひし形に並ぶ回廊。', 'Crystal pillars form a diamond.'],
    '從四個缺口鑽進中央吧！': ['4つのすき間から中へ入ろう！', 'Slip in through the four gaps!'],
    '女僕裝': ['メイド服', 'Maid Uniform'],
    '蕾絲咖啡廳的制服。': ['レース喫茶の制服。', 'The Lace Cafe uniform.'],
    '黑貓女僕裝': ['黒ネコメイド', 'Black Cat Maid'],
    '毛茸茸的貓耳朵是重點！': ['ふわふわのネコ耳がポイント！', 'The fluffy cat ears are the best part!'],
    '夏日浴衣': ['夏のゆかた', 'Summer Yukata'],
    '別上髮花的祭典浴衣。': ['髪に花を飾ったお祭りゆかた。', 'A festival yukata with a hair flower.'],
    '公主洋裝': ['プリンセスドレス', 'Princess Dress'],
    '閃亮亮的小皇冠。': ['キラキラの小さなティアラつき。', 'Comes with a sparkly tiara.'],
    '鑽頭機器人': ['ドリルロボ', 'Drill Bot'],
    '理科社社長': ['科学部の部長', 'Science Club Head'],
    '理科社的掃除機器人失控了！': ['科学部のそうじロボが暴走！', 'The science robot ran wild!'],
    '牠撞到硬牆會暈一下，趁機炸牠！': ['壁にぶつけて目を回したら攻撃！', 'Make it crash, then bomb it while dizzy!'],
    '火焰蜘蛛': ['ほのおグモ', 'Flame Spider'],
    '火焰沿著直線噴出，別跟牠站同一排！': ['炎はまっすぐ飛ぶ。同じ列はキケン！', 'Stay out of its row and column.'],
    '理科社做的掃除機器人。': ['科学部が作ったそうじロボ。', 'A cleaning robot built by the Science Club.'],
    '頭上燒著火焰的機械蜘蛛。': ['頭に炎を燃やす機械グモ。', 'A robot spider with a fire on its head.'],
    '讓別的女僕來值班。': ['ほかのメイドと交代する。', 'Switch the maid on duty.'],
    '金魚缸': ['金魚鉢', 'Fishbowl'],
    '每天餵魚，心情 +4。': ['毎日エサやりで気分 +4。', 'Feed it daily: mood +4.'],
    '梳妝台': ['ドレッサー', 'Vanity'],
    '每天梳妝打扮，心情 +6。': ['毎日おめかしで気分 +6。', 'Dress up daily: mood +6.'],
    '愛心沙發': ['ハートソファ', 'Heart Sofa'],
    '每天坐著休息，體力 +15。': ['毎日ひと休みで体力 +15。', 'Rest daily: STA +15.'],
    '留聲機': ['蓄音機', 'Gramophone'],
    '播放唱片，心情 +5。': ['レコードで気分 +5。', 'Play a record: mood +5.'],
    '用賺到的金幣買家具吧！點右上角的「佈置」': ['稼いだコインで家具を買おう！右上の「もようがえ」から', 'Buy furniture with your coins! Tap Decorate (top right)'],
    '抹茶羊羹': ['抹茶ようかん', 'Matcha Yokan'],
    '香草冰淇淋': ['バニラアイス', 'Vanilla Ice'],
    '玫瑰花束': ['バラの花束', 'Rose Bouquet'],
    '蕾絲髮帶': ['レースリボン', 'Lace Ribbon'],

    // ---- affection & training
    '陌生': ['初対面', 'Stranger'],
    '熟悉': ['顔なじみ', 'Familiar'],
    '委託開始時 SP +20': ['依頼開始時 SP+20', 'Start jobs with SP +20'],
    '信賴': ['信頼', 'Trusted'],
    '委託中愛心 +1': ['依頼中ハート+1', 'Hearts +1 on jobs'],
    '親密': ['仲良し', 'Close'],
    '委託報酬 +20%': ['依頼の報酬+20%', 'Job rewards +20%'],
    '最愛': ['大好き', 'Beloved'],
    '愛的守護：每次委託抵擋一次致命傷': ['愛のまもり：依頼ごとに1回やられない', 'Love Shield: survive one fatal hit per job'],
    '體能鍛鍊': ['体力づくり', 'Fitness'],
    'Lv2/4 愛心+1': ['Lv2/4 ハート+1', 'Lv2/4 Heart+1'],
    '愛心上限 +1（Lv2、Lv4）': ['ハート上限+1（Lv2・Lv4）', 'Max hearts +1 (Lv2, Lv4)'],
    '敏捷訓練': ['ダッシュ', 'Agility'],
    'Lv2/5 速度+1': ['Lv2/5 スピード+1', 'Lv2/5 Speed+1'],
    '速度 +1（Lv2、Lv5），受傷後無敵更久': ['スピード+1（Lv2・Lv5）、ダメージ後の無敵が長くなる', 'Speed +1 (Lv2, Lv5), longer invincibility after hits'],
    '爆破研究': ['ボム研究', 'Bomb Lab'],
    'Lv2 火力 Lv4 炸彈': ['Lv2火力 Lv4ボム', 'Lv2 Fire Lv4 Bomb'],
    '火力 +1（Lv2）、炸彈 +1（Lv4）': ['火力+1（Lv2）・ボム+1（Lv4）', 'Fire +1 (Lv2), Bombs +1 (Lv4)'],
    '家事練習': ['家事練習', 'Chores'],
    '打掃獎勵・省SP': ['そうじ報酬・SP節約', 'Dust bonus, SP saver'],
    '掃灰塵獎勵變多，特技更省 SP（Lv3、Lv5）': ['ホコリの報酬アップ、特技のSPが減る（Lv3・Lv5）', 'More from dust, cheaper skills (Lv3, Lv5)'],

    // ---- opening, guide, mornings
    '「蕾絲町」——一座被灰塵怪佔領的小鎮。': ['「レース町」——ホコリおばけに占領された小さな町。', 'Lace Town: a little town overrun by dust monsters.'],
    '你搬進洋館裡的一間小房間，成為新的主人。': ['あなたは洋館の小さな部屋に越してきた、新しいご主人さま。', 'You just moved into a small room in the old mansion.'],
    '為了打掃小鎮、賺點生活費……': ['町をきれいにして、生活費をかせぐため…', 'To clean up the town and earn a living...'],
    '你決定雇用一位女僕！': ['メイドを雇うことにした！', 'you decide to hire a maid!'],
    '把手套移到女僕頭上按 Z，摸摸她的頭': ['手ぶくろをメイドの頭に合わせて Z でなでなで', "Move the glove onto her head and press Z to pat"],
    '點女僕的身體打開選單，和她聊聊天': ['メイドの体をクリックしてメニューからおしゃべり', 'Click her body to open the menu, then talk'],
    '點書桌進行特訓，讓她變得更強': ['つくえをクリックして特訓しよう', 'Click the desk to train her'],
    '點下方的門口出門，接下第一個委託吧': ['下のドアからおでかけして、最初の依頼へ', 'Leave through the door below for your first job'],
    '{maid}烤了點心要送給你！': ['{maid}がお菓子を焼いてくれた！', '{maid} baked you a treat!'],
    '在床底下撿到了 40G！': ['ベッドの下で40G見つけた！', 'Found 40G under the bed!'],
    '{maid}一早就把房間擦得亮晶晶。': ['{maid}が朝からお部屋をぴかぴかに。', '{maid} polished the room this morning.'],
    '{maid}泡了早安紅茶，心情很好。': ['{maid}がモーニングティーをいれてごきげん。', '{maid} made morning tea and feels great.'],

    // ---- Berry: energetic karate girl
    '初次見面！我是莓果！從今天起就是主人的女僕了，請多指教！': ['はじめまして！ベリーです！今日からご主人さまのメイドです、よろしくお願いしますっ！', "Nice to meet you! I'm Berry, your maid from today on!"],
    '主人早安！今天也要元氣滿滿喔！': ['ご主人さま、おはようございます！今日も元気いっぱいです！', "Morning, Master! Full energy today!"],
    '主人！我已經熱身完畢了！': ['ご主人さま！準備運動ばっちりです！', "Master! I'm all warmed up!"],
    '嘿嘿，主人來啦～今天要做什麼？': ['えへへ、ご主人さま～今日は何します？', "Hehe, Master's here~ What's the plan?"],
    '欸嘿嘿……被摸頭了～': ['えへへ…なでなでされちゃった～', 'Ehehe... a head pat~'],
    '唔、主人的手好溫暖……': ['ん、ご主人さまの手、あったかい…', "Mm, your hand is so warm..."],
    '再、再摸一下也可以喔！': ['も、もう一回なでてもいいですよ！', 'Y-you can pat me once more!'],
    '主人，頭髮要被摸亂啦！': ['ご主人さま、髪がぐしゃぐしゃになっちゃう！', "Master, you're messing up my hair!"],
    '好、好了啦！夠了夠了！': ['も、もういいです！おしまい！', "O-okay! That's enough!"],
    '我小時候在道場練了十年空手道！': ['子どものころ、道場で10年空手をやってたんです！', 'I trained karate at a dojo for ten years!'],
    '打掃跟練拳一樣，靠的是氣勢！': ['おそうじも空手も、気合いが大事！', "Cleaning is like karate. It's all spirit!"],
    '主人的房間有點亂耶，我來整理！': ['お部屋がちょっと散らかってますね、片づけます！', "Your room's a little messy. I'll tidy up!"],
    '主人喜歡草莓嗎？我超喜歡的！': ['ご主人さま、いちご好きですか？私は大好き！', 'Do you like strawberries? I love them!'],
    '上次委託，我踢飛了好多炸彈喔！': ['この前の依頼、ボムをいっぱいけり飛ばしました！', 'I kicked so many bombs on the last job!'],
    '跟主人說話，心情就會變好呢！': ['ご主人さまと話すと元気が出ます！', 'Talking with you always cheers me up!'],
    '就算怪物再多，我也會保護主人！': ['モンスターがいくらいても、ご主人さまを守ります！', "No matter how many monsters come, I'll protect you!"],
    '主人，我們是最棒的搭檔對吧？': ['ご主人さま、私たち最高のコンビですよね？', "We're the best team, right, Master?"],
    '偷偷告訴你，我其實很怕打雷……': ['ないしょですけど、実はカミナリが苦手で…', "Between us... I'm actually scared of thunder..."],
    '能當主人的女僕，真的太好了。': ['ご主人さまのメイドになれて、本当によかった。', "I'm really glad I became your maid."],
    '主人……今天也可以待在我身邊嗎？': ['ご主人さま…今日もそばにいてくれますか？', 'Master... will you stay by my side today too?'],
    '最喜歡主人了！……啊，說出來了！': ['ご主人さま大好き！…あっ、言っちゃった！', 'I love you, Master! ...Ah, I said it!'],
    '不管去哪裡，莓果都跟著主人喔！': ['どこへでも、ベリーはご主人さまについていきます！', "Wherever you go, Berry's coming too!"],
    '今天聊好多喔！剩下的明天再說吧♪': ['今日はいっぱい話しました！続きはまた明日♪', "We talked so much today! More tomorrow♪"],
    '草莓大福！主人怎麼知道我最愛這個！': ['いちご大福！どうして大好物だってわかったんですか！', "Berry mochi! How did you know it's my favorite?!"],
    '謝謝主人！我會好好珍惜的！': ['ありがとうございます！大事にしますね！', "Thank you, Master! I'll treasure it!"],
    '今天收到好多禮物了，留到明天嘛！': ['今日はもうたくさんもらいました、また明日！', "I got plenty today. Save it for tomorrow!"],
    '呼～和主人喝茶好幸福喔。': ['ふぅ～ご主人さまとのお茶、しあわせです。', 'Phew~ Tea with you is the best.'],
    '呼……主人，讓我休息一下嘛……': ['はぁ…ご主人さま、ちょっと休ませて…', 'Huff... Master, let me rest a bit...'],
    '好！特訓開始！看我的！': ['よーし！特訓開始！見ててください！', "Okay! Training starts now! Watch me!"],
    '呼！流了好多汗，感覺變強了！': ['ふぅ！いい汗かいた、強くなった気がします！', "Whew! Good sweat. I feel stronger!"],
    '莓果，出擊！主人等我好消息！': ['ベリー、出撃！いい知らせを待っててください！', "Berry, heading out! Wait for good news!"],
    '我回來了！委託順利完成～': ['ただいまです！依頼ばっちり完了～', "I'm back! Job complete~"],
    '嗚嗚……被炸得黑漆漆的……': ['うう…まっ黒こげです…', 'Ugh... burnt to a crisp...'],
    '主人晚安……明天見……': ['おやすみなさい…また明日…', 'Good night, Master... see you tomorrow...'],
    '和主人的距離，好像又更近了一點呢！': ['ご主人さまとの距離、また近づいた気がします！', 'I feel even closer to you now!'],
    '嘿嘿，我只會彈「小星星」啦♪': ['えへへ、「きらきら星」しか弾けないんです♪', 'Hehe, I only know "Twinkle Twinkle"♪'],

    // ---- Yoru: stoic swordswoman
    '初次見面，主人。我是夜子。今後，請讓我侍奉您。': ['はじめまして、ご主人さま。夜子と申します。今後、お仕えさせていただきます。', 'A pleasure, Master. I am Yoru. Please allow me to serve you.'],
    '主人，早安。今天的行程已經準備好了。': ['おはようございます、ご主人さま。本日の予定は整えてあります。', "Good morning, Master. Today's schedule is prepared."],
    '……主人，您來了。': ['…ご主人さま、いらしたのですね。', '...Master. You have arrived.'],
    '今日天氣晴。適合斬灰塵。': ['本日は晴天。ホコリを斬るには良い日です。', 'Clear skies today. A fine day for cutting dust.'],
    '……！主、主人，請不要突然這樣。': ['…！ご、ご主人さま、急にそういうことは…', '...! M-Master, please do not do that so suddenly.'],
    '……並不討厭。': ['…嫌では、ありません。', '...I do not dislike it.'],
    '咳。請、請繼續……不，沒事。': ['こほん。つ、続けて…いえ、何でもありません。', 'Ahem. P-please continue... no, never mind.'],
    '主人，請適可而止。': ['ご主人さま、ほどほどに。', 'Master, that is quite enough.'],
    '……再摸下去，我要拔刀了。': ['…これ以上は、抜刀いたします。', '...Any more and I draw my blade.'],
    '我的刀名叫「月見」，是祖母傳下來的。': ['この刀は「月見」。祖母から受け継いだものです。', 'My sword is named Tsukimi. It came from my grandmother.'],
    '保持房間整潔，就是保持心的整潔。': ['部屋を整えることは、心を整えること。', 'A tidy room is a tidy heart.'],
    '請放心，我會完成每一個委託。': ['ご安心を。どの依頼も必ず果たします。', 'Rest assured. I will complete every job.'],
    '抹茶配上和菓子，是最好的休息。': ['抹茶と和菓子こそ、至高の休息です。', 'Matcha with wagashi is the finest rest.'],
    '主人今天看起來很有精神，太好了。': ['ご主人さま、今日はお元気そうで何よりです。', 'You look well today, Master. I am glad.'],
    '打掃時，我喜歡聽掃把的聲音。': ['掃除のとき、ほうきの音を聴くのが好きです。', 'I like the sound of the broom when I clean.'],
    '主人的背後，就由我來守護。': ['ご主人さまの背中は、私がお守りします。', 'I will guard your back, Master.'],
    '……我其實不太擅長和人說話。': ['…実は、人と話すのは得意ではありません。', '...In truth, I am not good at conversation.'],
    '和主人在一起時，心情很平靜。': ['ご主人さまといると、心が落ち着きます。', 'My heart is calm when I am with you.'],
    '主人，這是我做的護身符。請收下。': ['ご主人さま、私が作ったお守りです。どうぞ。', 'Master, I made this charm for you. Please take it.'],
    '……如果是主人的話，叫我小夜也可以。': ['…ご主人さまになら、「よるちゃん」と呼ばれても。', '...You may call me Yoru-chan. Only you.'],
    '我的刀，還有我的心，都屬於主人。': ['この刀も、この心も、ご主人さまのものです。', 'My blade and my heart both belong to you.'],
    '……主人，請一直待在我身邊。': ['…ご主人さま、ずっとおそばにいてください。', '...Master, please stay by my side always.'],
    '今天已經說了很多話……我有點不習慣。': ['今日はたくさん話しました…少し慣れません。', 'I have spoken a great deal today... I am not used to it.'],
    '抹茶……！主人，您真是……謝謝您。': ['抹茶…！ご主人さま、あなたという方は…ありがとうございます。', 'Matcha...! Master, you truly... thank you.'],
    '謝謝主人。我會好好收藏。': ['ありがとうございます。大切にいたします。', 'Thank you, Master. I will keep it safe.'],
    '主人，今天的心意已經足夠了。': ['ご主人さま、本日のお気持ちはもう十分です。', 'Master, your kindness today is already enough.'],
    '茶的溫度剛好。主人很懂呢。': ['お茶の温度がちょうどいい。さすがです。', 'The tea is the perfect temperature. Well done.'],
    '……抱歉，主人。請讓我稍微歇息。': ['…申し訳ありません。少し休ませてください。', '...Forgive me, Master. Let me rest a little.'],
    '修行開始。請主人在一旁看著。': ['修行を始めます。どうぞ見守っていてください。', 'Training begins. Please watch over me.'],
    '……刀法又精進了一分。': ['…剣の腕が、また一つ磨かれました。', '...My swordsmanship sharpened a little more.'],
    '夜子，出陣。': ['夜子、出陣します。', 'Yoru, heading into battle.'],
    '任務完成。灰塵已全數斬除。': ['任務完了。ホコリはすべて斬りました。', 'Mission complete. All dust has been cut down.'],
    '……是我修行不足。下次一定。': ['…修行不足でした。次こそは。', '...My training was lacking. Next time, surely.'],
    '主人，晚安。請做個好夢。': ['おやすみなさいませ。よい夢を。', 'Good night, Master. Sweet dreams.'],
    '……主人。今後也請多多指教。': ['…ご主人さま。これからもよろしくお願いいたします。', '...Master. I look forward to our days ahead.'],
    '……這首是祖母教我的曲子。': ['…祖母に教わった曲です。', '...My grandmother taught me this song.'],

    // ---- Honey: sweet baker
    '主人好～我是蜜糖！以後每天都做點心給主人吃喔♪': ['ご主人さま～ハニーです！毎日お菓子を作ってあげますね♪', "Hi, Master~ I'm Honey! I'll bake treats for you every day♪"],
    '主人早安～今天的點心是鬆餅喔♪': ['おはようございます～今日のおやつはパンケーキですよ♪', "Morning~ Today's treat is pancakes♪"],
    '哇～主人來了！蜜糖好開心♪': ['わぁ～ご主人さまだ！ハニーうれしい♪', 'Yay~ Master is here! Honey is so happy♪'],
    '主人主人～今天要一起做什麼呀？': ['ご主人さま～今日はいっしょに何しますか？', "Master, Master~ What shall we do today?"],
    '嘿嘿～主人的手好溫柔♪': ['えへへ～ご主人さまの手、やさしい♪', 'Hehe~ Your hand is so gentle♪'],
    '喵～被摸得好舒服～': ['にゃ～気持ちいい～', 'Nya~ that feels nice~'],
    '再多摸摸人家嘛～♪': ['もっとなでなでして～♪', 'Pat me more~♪'],
    '唔～雙馬尾要塌掉了啦！': ['むぅ～ツインテールがくずれちゃう！', 'Mmh~ my twin tails are coming undone!'],
    '主人好貪心喔～今天夠了啦♪': ['ご主人さまったら欲ばり～今日はおしまい♪', "So greedy, Master~ That's all for today♪"],
    '蜜糖最會烤蛋糕了，下次做給主人吃！': ['ハニーはケーキ作りが得意！今度作ってあげます！', "Honey's great at cakes! I'll bake you one soon!"],
    '炸彈也可以做成甜點的形狀喔♪': ['ボムもお菓子の形にできるんですよ♪', 'Bombs can be shaped like desserts too♪'],
    '雙馬尾每天都要捲好久呢～': ['ツインテールは毎朝巻くのが大変なんです～', 'Curling my twin tails takes forever every morning~'],
    '主人喜歡甜的還是鹹的呀？': ['ご主人さまは甘いのとしょっぱいの、どっちが好き？', 'Do you like sweet or salty, Master?'],
    '蜂蜜蛋糕的秘訣是……愛心喔♪': ['ハニーケーキの秘密は…愛情です♪', 'The secret to honey cake is... love♪'],
    '跟主人在一起，每天都甜甜的～': ['ご主人さまといると、毎日あまあま～', "With you, every day is sweet~"],
    '蜜糖受傷的話，主人會心疼嗎？': ['ハニーがケガしたら、ご主人さま心配してくれる？', 'Would you worry if Honey got hurt?'],
    '主人累了，蜜糖的魔法分你一點♪': ['ご主人さまが疲れたら、ハニーの魔法をおすそわけ♪', "When you're tired, I'll share my magic♪"],
    '主人是蜜糖的專屬試吃員喔！': ['ご主人さまはハニー専属の味見係です！', "You're Honey's official taste tester!"],
    '主人……蜜糖可以一直待在這裡嗎？': ['ご主人さま…ハニー、ずっとここにいてもいい？', 'Master... can Honey stay here forever?'],
    '今天的蛋糕，只做給主人一個人♪': ['今日のケーキは、ご主人さまだけの特別♪', "Today's cake is just for you♪"],
    '最～最～最喜歡主人了♪': ['だーいだーい大好き♪', 'I love love LOVE you, Master♪'],
    '蜜糖的心，已經融化成蜂蜜了啦……': ['ハニーの心、はちみつみたいにとろけちゃった…', "Honey's heart has melted like honey..."],
    '今天說了好多話，嘴巴都甜甜的了～': ['今日はいっぱいおしゃべりして、お口があまあま～', 'We talked so much my mouth tastes sweet~'],
    '蜂蜜蛋糕！！主人最棒了～♪': ['ハニーケーキ！！ご主人さま最高～♪', "Honey cake!! You're the best, Master~♪"],
    '哇～謝謝主人！蜜糖好開心♪': ['わぁ～ありがとう！ハニーうれしい♪', 'Wow~ thank you! Honey is so happy♪'],
    '今天的禮物夠多啦，明天再給蜜糖嘛♪': ['今日はもう十分！また明日ちょうだいね♪', "That's plenty for today! More tomorrow♪"],
    '配上點心的午茶時間最幸福了～': ['お菓子つきのティータイムがいちばん幸せ～', 'Tea time with sweets is pure bliss~'],
    '嗚～蜜糖累累了……想睡午覺……': ['ふぇ～ハニー疲れちゃった…お昼寝したい…', "Uu~ Honey's tired... I want a nap..."],
    '蜜糖也會努力的！加油加油～': ['ハニーもがんばる！ファイト～', "Honey will do her best! Go go~"],
    '好累喔～但是變強了呢♪': ['つかれた～でも強くなったよ♪', "So tired~ but I got stronger♪"],
    '蜜糖出發囉～主人要乖乖等我♪': ['ハニー、いってきまーす♪いい子で待っててね♪', "Honey's off~ Wait for me like a good master♪"],
    '我回來了～有沒有想蜜糖呀？': ['ただいま～ハニーのこと恋しかった？', "I'm home~ Did you miss Honey?"],
    '嗚嗚……奶油都烤焦了……': ['うう…クリームがこげちゃった…', 'Waah... my frosting got burnt...'],
    '晚安，主人～夢裡也要一起吃蛋糕喔♪': ['おやすみなさい～夢の中でもケーキ食べようね♪', "Good night~ Let's eat cake in our dreams too♪"],
    '主人對蜜糖的好感度……爆表了♪': ['ご主人さまへの好き、あふれちゃった♪', 'My love for you just overflowed♪'],
    '這首曲子叫「鬆餅圓舞曲」喔♪': ['この曲は「パンケーキのワルツ」です♪', 'This one is called "Pancake Waltz"♪'],

    // ---- Yukino: cool, bookish, a little tsundere
    '我是雪乃。……既然被雇用了，我會盡到女僕的責任。': ['雪乃です。…雇われた以上、メイドの務めは果たします。', "I'm Yukino. ...Since you hired me, I'll do my job properly."],
    '早安，主人。今天的最佳行動已經算好了。': ['おはようございます。本日の最適な行動は計算済みです。', "Morning, Master. Today's optimal plan is already calculated."],
    '……主人，你遲到了三分鐘。': ['…ご主人さま、3分遅刻です。', "...Master, you're three minutes late."],
    '早。昨晚的資料我整理完了。': ['おはよう。昨夜のデータは整理しておきました。', 'Morning. I sorted last night\'s data.'],
    '……這不在我的計算之內。': ['…これは計算外です。', '...This was not in my calculations.'],
    '我、我又不是小孩子……！': ['わ、私は子どもじゃありません…！', "I-I'm not a child...!"],
    '……只准再摸一下。': ['…あと一回だけ、許可します。', '...One more pat. That is all.'],
    '主人，摸頭次數已超過合理範圍。': ['なでなで回数が合理的な範囲を超えました。', 'Head pats have exceeded a reasonable range.'],
    '眼鏡要歪了啦……真是的。': ['メガネがずれるでしょう…もう。', 'My glasses are slipping... honestly.'],
    '爆炸威力和火力等級成正比。': ['爆発の威力は火力レベルに比例します。', 'Blast power is proportional to fire level.'],
    '我讀過三百本關於清潔的書。': ['掃除に関する本を300冊読みました。', "I've read three hundred books on cleaning."],
    '主人，請把書放回書櫃。': ['ご主人さま、本は本だなに戻してください。', 'Master, please put books back on the shelf.'],
    '冰淇淋的最佳溫度是零下十三度。': ['アイスの最適温度はマイナス13度です。', 'The ideal ice cream temperature is minus thirteen degrees.'],
    '……主人的判斷，偶爾也挺正確的。': ['…ご主人さまの判断も、たまには正しいですね。', '...Your judgment is occasionally correct.'],
    '遙控引爆的時機，全靠計算。': ['リモコン起爆のタイミングは、すべて計算です。', 'Remote blast timing is all calculation.'],
    '我替主人做了委託的攻略筆記。': ['ご主人さまのために依頼の攻略ノートを作りました。', 'I made you strategy notes for the jobs.'],
    '和主人在一起的時間……效率很高。': ['ご主人さまといる時間は…効率がいいです。', 'Time with you is... very efficient.'],
    '……並不是特別想見你才來的。': ['…べ、別に会いたくて来たわけじゃありません。', "...It's not like I came because I wanted to see you."],
    '我們相處的天數，我都記得喔。': ['一緒に過ごした日数、ちゃんと覚えています。', 'I remember every day we have spent together.'],
    '算了很多次……答案都是主人。': ['何度計算しても…答えはご主人さまでした。', 'I calculated it many times... the answer is always you.'],
    '……喜歡。這是經過驗算的結論。': ['…好きです。検算済みの結論です。', '...I like you. That conclusion has been verified.'],
    '主人，今後也請一直做我的研究對象。': ['ご主人さま、これからもずっと私の研究対象でいてください。', 'Master, please remain my research subject forever.'],
    '今日對話量已達上限。明天再說。': ['本日の会話量は上限です。続きは明日。', "Today's conversation limit reached. Continue tomorrow."],
    '冰淇淋……！咳，我只是剛好想吃而已。': ['アイス…！こほん、ちょうど食べたかっただけです。', "Ice cream...! Ahem, I just happened to want some."],
    '……謝謝。我會好好保存的。': ['…ありがとう。大切に保管します。', "...Thank you. I'll keep it safe."],
    '禮物太多會影響判斷。明天再給我。': ['プレゼントが多いと判断が鈍ります。明日にしてください。', 'Too many gifts cloud my judgment. Tomorrow, please.'],
    '紅茶有助於思考。主人也喝一點吧。': ['紅茶は思考を助けます。ご主人さまもどうぞ。', 'Tea helps thinking. Have some too, Master.'],
    '能量不足……主人，建議休息。': ['エネルギー不足…休息を推奨します。', 'Energy low... I recommend rest.'],
    '特訓計畫，開始執行。': ['特訓プラン、実行開始。', 'Training plan: executing.'],
    '數據提升了。符合預期。': ['数値が上昇しました。予測どおりです。', 'Stats improved. As predicted.'],
    '雪乃，出發。會準時回來的。': ['雪乃、出発します。時間どおりに戻ります。', "Yukino, departing. I'll be back on schedule."],
    '委託完成。誤差在容許範圍內。': ['依頼完了。誤差は許容範囲内です。', 'Job complete. Error within tolerance.'],
    '……計算錯誤。我會修正的。': ['…計算ミスです。修正します。', "...Calculation error. I'll correct it."],
    '晚安，主人。……明天見。': ['おやすみなさい。…また明日。', 'Good night, Master. ...See you tomorrow.'],
    '好感度參數……上升了。不是壞事。': ['好感度パラメータ…上昇。悪くないです。', 'Affection parameter... rising. Not a bad thing.'],
    '這首的節拍，我練習了一百次。': ['この曲のテンポ、100回練習しました。', 'I practiced this tempo one hundred times.'],
  });
})(window);
